/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "GUI_Main.h"
#if GUI_OPERATING > 0u
	#include "includes.h"
#endif


/***********************************************************************
*       控件ID定义  (控件ID = 页面基本ID + 控件偏移ID)
************************************************************************
*/
#define ID_APP_Reserved_FRAMEWIN    (GUI_ID_USER + APP_Reserved_BASE_ID + 0x00)            //预留APP页面ID

/***********************************************************************
*                             对话框资源表
************************************************************************
*/
/* 保留APP对话框 */
static const GUI_WIDGET_CREATE_INFO Dialog_APP_Reserved_Create[] =
{
  { FRAMEWIN_CreateIndirect, "Reserved", ID_APP_Reserved_FRAMEWIN, NEW_APP_COORDINATE_X, NEW_APP_COORDINATE_Y, NEW_APP_WIDTH, NEW_APP_HIGHT, 0, 0x64, 0 },
};

/************************************************************************************************************************
*
*       变量声明
*
*************************************************************************************************************************
*/
#if GUI_OPERATING > 0u
	extern OS_TCB  AppTaskMusicTCB;
	static MusicMsg_T s_tMusicMsg;            		 /* 用于给音乐播放任务发消息，发送音乐类型和歌曲路径 */
#endif
/* APP窗口句柄 */
extern WM_HWIN hWinReservedTask;       //预留APP窗口句柄
/************************************************************************************************************************
*
*       静态代码
*
*************************************************************************************************************************
*/
/**
  * @brief 保留APP窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Reserved(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;

	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针
	(void)hItem;

	#if GUI_OPERATING > 0u
		OS_ERR  err;
	#endif
	
	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
	#if APP_Reserved_WINDOW_DEFAULT > 0u
		/* app窗口初始化 */
		FRAMEWIN_SetBarColor(hWin, 1, NEW_APP_BAR_COLOR_ENALBE);                //窗口标题栏颜色
		FRAMEWIN_SetBarColor(hWin, 0, NEW_APP_BAR_COLOR_UNENALBE);
		#if GUI_LANGUAGE > 0u
			FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                                  //窗口文本字体
			FRAMEWIN_SetText(hWin, "预留APP");                                     //窗口文本
		#else
			FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
			FRAMEWIN_SetText(hWin, "Reserved");                            //窗口文本
		#endif
		FRAMEWIN_SetTextAlign(hWin, NEW_APP_BAR_ALIGN);                         //标题栏文本对齐方式
		FRAMEWIN_SetTitleHeight(hWin, NEW_APP_BAR_HIGHT);

		/* 初始化窗口性质 */
		if (NEW_APP_CLOSEBUTTON > 0u)
		{
			FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
		}
		if (NEW_APP_ACTIVE > 0u)
		{
			FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
		}
	#else
		/* 用户定义区 */

		/* 用户定义区结束 */
	#endif
//		#if GUI_OPERATING > 0u
//			GUI_Delay(1000);
//			wm8978_SetSpkVolume(25);
//			s_tMusicMsg.ucName = (uint8_t *)"0:/Music/1.wav";
//			s_tMusicMsg.ucType = MusicType_WAV;
//		
//			/* 发消息，播放新歌 */
//			OSTaskQPost(&AppTaskMusicTCB,
//						(void *)&s_tMusicMsg,   /* 数据地址 */
//						sizeof(s_tMusicMsg),    /* 数据字节数，也可以不是字节数，保证发送和接收统一即可 */
//						OS_OPT_POST_FIFO,
//						&err);
//					
//			OSFlagPost ((OS_FLAG_GRP  *)&FLAG_Music,
//						(OS_FLAGS      )MusicTaskAudioPlay_5, 
//						(OS_OPT        )OS_OPT_POST_FLAG_SET,
//						(OS_ERR       *)&err);
//					
//			//printf("发送消息%s\n\r",s_tMusicMsg.ucName);
//		#endif
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}

}
/* function end */


/************************************************************************************************************************
*
*       公共代码
*
*************************************************************************************************************************
*/
/**
  * @brief 保留APP窗口创建函数
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Reserved_Create(void)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Reserved_Create, GUI_COUNTOF(Dialog_APP_Reserved_Create), _cbAPP_Reserved, WM_HBKWIN, 0, 0);
	return hWin;
}
/*************************** End of file ****************************/
