/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "GUI_Main.h"
#include "GUI_Clock_DLG.h"
#include "GUI_Calendar_DLG.h"
#if GUI_OPERATING > 0u
	#include "includes.h"
#endif

/************************************************************************************************************************
*
*       变量声明
*
*************************************************************************************************************************
*/
/* APP窗口句柄 */
extern WM_HWIN hWinCalenderTask;       //万年历APP窗口句柄
/* 系统时间结构体 */
#if GUI_OPERATING == 0u
	extern RTC_T g_tRTC;
#endif
/* 系统时间显示变量 */
extern char System_Date_Display[15];         //xxxx年xx月xx日
extern char System_Time_Display[9];          //xx:xx:xx

#if GUI_LANGUAGE > 0u
	const char* apWeek[7] =
	{
		"星期一",
		"星期二",
		"星期三",
		"星期四",
		"星期五",
		"星期六",
		"星期日",
	};
#else
	const char* apWeek[7] =
	{
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday",
		"Sunday",
	};
#endif
#if GUI_LANGUAGE > 0u
	const char* apDays[8] =
	{
		"六",
		"日",
		"一",
		"二",
		"三",
		"四",
		"五",
		"六",
	};
	const char* apMonths[12] =
	{
		"1月",
		"2月",
		"3月",
		"4月",
		"5月",
		"6月",
		"7月",
		"8月",
		"9月",
		"10月",
		"11月",
		"12月",
	};
#endif

/************************************************************************************************************************
*
*       静态代码
*
*************************************************************************************************************************
*/
/**
  * @brief 系统设置——应用窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Calender(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;
	
	(void) NCode;
	(void) Id;
	
	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		#if APP_Calender_WINDOW_DEFAULT > 0u
			/* app窗口初始化 */
			FRAMEWIN_SetBarColor(hWin, 1, NEW_APP_BAR_COLOR_ENALBE);                //窗口标题栏颜色
			FRAMEWIN_SetBarColor(hWin, 0, NEW_APP_BAR_COLOR_UNENALBE);
			#if GUI_LANGUAGE > 0u
				FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);                                  //窗口文本字体
				FRAMEWIN_SetText(hWin, "万年历");                                     //窗口文本
			#else
				FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
				FRAMEWIN_SetText(hWin, "Calendar");                                      //窗口文本
			#endif
			FRAMEWIN_SetTextAlign(hWin, NEW_APP_BAR_ALIGN);                         //标题栏文本对齐方式
			FRAMEWIN_SetTitleHeight(hWin, NEW_APP_BAR_HIGHT);

			/* 初始化窗口性质 */
			if (NEW_APP_CLOSEBUTTON > 0u)
			{
				FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
			}
			if (NEW_APP_ACTIVE > 0u)
			{
				FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
			}
		#else
			/* 用户定义区 */
			/* 用户定义区结束 */
		#endif
		/* 日历控件初始化 */
		CALENDAR_SetDefaultSize(CALENDAR_SI_HEADER, 40);
		CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_X, 100);
		CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_Y, 40);
		#if GUI_LANGUAGE > 0u
			CALENDAR_SetDefaultDays(apDays);
			CALENDAR_SetDefaultMonths(apMonths);
			CALENDAR_SetDefaultFont(CALENDAR_FI_CONTENT, &GUI_FontHZ24);
			CALENDAR_SetDefaultFont(CALENDAR_FI_HEADER, &GUI_FontHZ24);
		#else
			CALENDAR_SetDefaultFont(CALENDAR_FI_CONTENT, GUI_FONT_24B_1);
			CALENDAR_SetDefaultFont(CALENDAR_FI_HEADER, GUI_FONT_24B_1);
		#endif
		CALENDAR_SetDefaultBkColor(CALENDAR_CI_WEEKDAY, GUI_WHITE);               //设置日历颜色
		CALENDAR_SetDefaultBkColor(CALENDAR_CI_WEEKEND, GUI_WHITE);
		CALENDAR_SetDefaultBkColor(CALENDAR_CI_SEL, GUI_BLUE);
		CALENDAR_SetDefaultBkColor(CALENDAR_CI_HEADER, GUI_LIGHTBLUE);
		/* 获取系统时间 */
		#if GUI_OPERATING > 0u
			RTC_ReadClock();
		#endif
		/* 在指定位置创建CALENDAR控件 */
		CALENDAR_Create(hWin,                     /* 父窗口句柄 */
			50,                                   /* 相对于父窗口坐标的最左像素 */
			70,                                   /* 相对于父窗口坐标的最上像素 */
			g_tRTC.Year,         /* 起始年份 */
			g_tRTC.Mon,          /* 起始月份 */
			g_tRTC.Day,          /* 起始日期 */
			2,                                    /* 每周起始星期 */
			ID_APP_Calendar_CALENDAR,             /* 控件ID */
			WM_CF_SHOW);                          /* 窗口创建标志*/
		/* 初始化文本控件 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_StrDate_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "日期：");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Date:");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_StrTime_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "时间：");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Time:");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Date_TEXT);
		#if GUI_LANGUAGE > 0u
			sprintf(System_Date_Display, "%0.4d/%0.2d/%0.2d",
					g_tRTC.Year,
					g_tRTC.Mon,
					g_tRTC.Day);
			TEXT_SetText(hItem, System_Date_Display);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			sprintf(System_Date_Display, "20%0.2d/%0.2d/%0.2d",
					g_tRTC.Year,
					g_tRTC.Mon,
					g_tRTC.Day);
			TEXT_SetText(hItem, System_Date_Display);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Week_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, apWeek[g_tRTC.Week - 1]);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, apWeek[g_tRTC.Week - 1]);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Time_TEXT);
		sprintf(System_Time_Display, "%0.2d:%0.2d:%0.2d",
				g_tRTC.Hour,
				g_tRTC.Min,
				g_tRTC.Sec);
		TEXT_SetText(hItem, System_Time_Display);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:	
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					//清屏
		GUI_SetColor(GUI_BLACK);
		GUI_DrawRect(44, 25, 746, 347);
		GUI_DrawRect(43, 24, 747, 348);
		/* 获取系统时间 */
		#if GUI_OPERATING > 0u
			RTC_ReadClock();
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Date_TEXT);
		#if GUI_LANGUAGE > 0u
			sprintf(System_Date_Display, "%0.4d/%0.2d/%0.2d",
					g_tRTC.Year,
					g_tRTC.Mon,
					g_tRTC.Day);
			TEXT_SetText(hItem, System_Date_Display);
		#else
			sprintf(System_Date_Display, "20%0.2d/%0.2d/%0.2d",
					g_tRTC.Year,
					g_tRTC.Mon,
					g_tRTC.Day);
			TEXT_SetText(hItem, System_Date_Display);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Week_TEXT);
		TEXT_SetText(hItem, apWeek[g_tRTC.Week - 1]);
		hItem = WM_GetDialogItem(hWin, ID_APP_Calendar_Time_TEXT);
		sprintf(System_Time_Display, "%0.2d:%0.2d:%0.2d",
				g_tRTC.Hour,
				g_tRTC.Min,
				g_tRTC.Sec);
		TEXT_SetText(hItem, System_Time_Display);
		break;

	case WM_NOTIFY_PARENT:
		break;

	case WM_TIMER:
		WM_Paint(WM_GetClientWindow(hWinCalenderTask));
    	WM_RestartTimer(pMsg->Data.v, 1000);
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */


/************************************************************************************************************************
*
*       公共代码
*
*************************************************************************************************************************
*/
/**
  * @brief 应用窗口创建函数--账号管理
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Calender_Create(void)
{
	WM_HWIN hWin;
	WM_HWIN hTimer;
	(void) hTimer;    //空指针
	hWin = GUI_CreateDialogBox(Dialog_APP_Calender_Create, GUI_COUNTOF(Dialog_APP_Calender_Create), _cbAPP_Calender, WM_HBKWIN, 0, 0);
	hTimer = WM_CreateTimer(WM_GetClientWindow(hWin), 0, 1000, 0);       //创建定时器
	return hWin;
}
/*************************** End of file ****************************/
