/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "DIALOG.h"
#include "GUI_Main.h"
#include "GUI_Setting_DLG.h"
#if GUI_OPERATING > 0u
	#include "includes.h"
#endif

/************************************************************************************************************************
*
*       变量声明
*
*************************************************************************************************************************
*/
/* 星期数组 */
extern const char* apWeek[7];
extern const char* apDays[8];
extern const char* apMonths[12];
extern char System_Date[11];                 //系统日期
extern char System_Time_Display[9];          //xx:xx:xx
/* APP窗口句柄 */
extern WM_HWIN hWinSettingsTask;       //系统设置APP窗口句柄
/* 桌面图标数组 */
#if GUI_LANGUAGE > 0u
static char* Setting_ListBox[8] =
{
	{"通用设置"}, {"系统时间"},{"无线网络"},{"蓝牙连接"},{"桌面和壁纸"},{"音量设置"},{"内存管理"},{"电池管理"}
};
#else
static char* Setting_ListBox[8] =
{
	{"General Setting"}, {"Time and Date"}, {"WLAN"}, {"Bluetooth"}, {"Background"}, {"Volume"}, {"Memory"}, {"Battery"}
};
#endif	
/* 当前选中窗口句柄 */
WM_HWIN hAPP_Settings_CurrentPage;                     //系统设置APP应用当前页面句柄
/* 系统设置标志位 */
uint8_t Background_enabled_bit = Background_Enable;                      //桌面背景启用标志位
uint8_t Time_modify_enabled_bit = System_Time_Modify_Enable;             //系统时间修改标志位
uint8_t Voice_Broadcast_enabled_bit = Voice_Broadcast_Modify_Enable;     //系统语音播报标志位
/************************************************************************************************************************
*
*       静态代码
*
*************************************************************************************************************************
*/
/**
  * @brief 系统设置——应用窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	WM_HWIN hListBox;
	
	int NCode;
	int Id;
	unsigned char i;
	unsigned char choose;

	(void)NCode;        //空指针
	(void)Id;           //空指针
	(void)hItem;
	
	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:

		#if APP_Settings_WINDOW_DEFAULT > 0u
			/* app窗口初始化 */
			FRAMEWIN_SetBarColor(hWin, 1, NEW_APP_BAR_COLOR_ENALBE);                //窗口标题栏颜色
			FRAMEWIN_SetBarColor(hWin, 0, NEW_APP_BAR_COLOR_UNENALBE);
			#if GUI_LANGUAGE > 0u
				FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);                                  //窗口文本字体
				FRAMEWIN_SetText(hWin, "系统设置");                                     //窗口文本
			#else
				FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
				FRAMEWIN_SetText(hWin, "Setting");                                      //窗口文本
			#endif
			FRAMEWIN_SetTextAlign(hWin, NEW_APP_BAR_ALIGN);                         //标题栏文本对齐方式
			FRAMEWIN_SetTitleHeight(hWin, NEW_APP_BAR_HIGHT);

			/* 初始化窗口性质 */
			if (NEW_APP_CLOSEBUTTON > 0u)
			{
				FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
			}
			if (NEW_APP_ACTIVE > 0u)
			{
				FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
			}
		#else
		/* 用户定义区 */

		/* 用户定义区结束 */
		#endif
		hListBox = WM_GetDialogItem(hWin, ID_APP_Settings_LISTBOX);              //获取列表框控件句柄
		for (i = 0; i < 8; i++)
		{
			LISTBOX_AddString(hListBox, Setting_ListBox[i]);
		}
		LISTBOX_SetTextAlign(hListBox, GUI_TA_LEFT | GUI_TA_VCENTER);
		#if GUI_LANGUAGE > 0u
			LISTBOX_SetFont(hListBox, &GUI_FontHZ24);                                  //窗口文本字体
		#else
			LISTBOX_SetFont(hListBox, GUI_FONT_24B_1);                               //窗口文本字体
		#endif
		LISTBOX_SetItemSpacing(hListBox, 30);
		 hAPP_Settings_CurrentPage = FUN_APP_Settings_Window1_Create(WM_GetClientWindow(hWin));

		break;

	case WM_PAINT:	
		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id) 
		{
		case ID_APP_Settings_LISTBOX: 
			switch (NCode) 
			{
			case WM_NOTIFICATION_CLICKED:

				break;
			case WM_NOTIFICATION_RELEASED:
	
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				GUI_EndDialog(WM_GetClientWindow(hAPP_Settings_CurrentPage), 0);
				choose = LISTBOX_GetSel(WM_GetDialogItem(hWin, ID_APP_Settings_LISTBOX));
				if (choose == 0)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window1_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 1)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window2_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 2)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window3_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 3)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window4_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 4)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window5_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 5)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window6_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 6)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window7_Create(WM_GetClientWindow(hWin))
					;
				else if (choose == 7)
					hAPP_Settings_CurrentPage = FUN_APP_Settings_Window8_Create(WM_GetClientWindow(hWin))
					;
				break;
			}
			break;
		}
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */

/**
  * @brief 系统设置第一页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window1(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "系统通用设置");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "General System Settings");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Background_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "桌面背景设置");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Desktop Background Settings");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Timemodify_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "修改系统时间日期");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Modifying the Date and Time");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Broadcast_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "系统语音播报");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Voice Broadcast");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Background_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Background_enabled_bit);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "使用桌面壁纸");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Use picture background");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Timemodify_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Time_modify_enabled_bit);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "允许修改系统时间日期");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "The system time and date can be modified");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Broadcast_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Voice_Broadcast_enabled_bit);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "允许系统语音播报");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "System voice broadcast is enabled");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					//清屏
		GUI_DrawGradientH(0, 0, 600, 440, GUI_LIGHTCYAN, GUI_LIGHTMAGENTA);
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件 ID */
		Id = WM_GetId(pMsg->hWinSrc);
		/* 获取消息内容 */
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_APP_Settings_Window1_Background_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Background_CHECKBOX);
				Background_enabled_bit = CHECKBOX_GetState(hItem);
				if (Background_enabled_bit == Background_Enable)
				{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "使用桌面壁纸");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "Use picture background");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
					}
					else
					{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "使用渐变色背景");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "Use gradient background");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
				}
				break;
			}
			break;
		case ID_APP_Settings_Window1_Timemodify_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Timemodify_CHECKBOX);
				Time_modify_enabled_bit = CHECKBOX_GetState(hItem);
				if (Time_modify_enabled_bit == System_Time_Modify_Enable)
				{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "允许修改系统时间日期");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "The system time and date can be modified");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
				}
				else
				{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "不允许修改系统时间日期");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "The system time and date can't be modified");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
				}
				break;
			}
			break;
		case ID_APP_Settings_Window1_Broadcast_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window1_Broadcast_CHECKBOX);
				Voice_Broadcast_enabled_bit = CHECKBOX_GetState(hItem);
				if (Voice_Broadcast_enabled_bit == Voice_Broadcast_Modify_Enable)
				{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "允许系统语音播报");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "System voice broadcast is enabled");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
			}
				else
				{
					#if GUI_LANGUAGE > 0u
						CHECKBOX_SetText(hItem, "不允许系统语音播报");
						CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
					#else
						CHECKBOX_SetText(hItem, "System voice broadcast is disabled");
						CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
					#endif
				}
				break;
			}
			break;
		default:
			WM_DefaultProc(pMsg);
			break;
		}
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */

/**
  * @brief 用户绘制函数
  * @note 无
  * @param pDrawItemInfo：指向WIDGET_ITEM_DRAW_INFO结构的指针
  * @retval 默认绘制函数 或 0
  */
static int Time_Setting_ListwheelDraw(const WIDGET_ITEM_DRAW_INFO* pDrawItemInfo)
{
	GUI_RECT aRect;
	switch (pDrawItemInfo->Cmd)
	{
	case WIDGET_ITEM_DRAW_OVERLAY:
		/* 获取控件坐标 */
		aRect.x0 = pDrawItemInfo->x0;
		aRect.x1 = pDrawItemInfo->x1;
		aRect.y1 = pDrawItemInfo->y1;
		/* 画分割线 */
		GUI_SetColor(GUI_BLACK);
		GUI_DrawLine(aRect.x0, (aRect.y1 - 19 - 16) / 2, aRect.x1, (aRect.y1 - 19 - 16) / 2);
		GUI_DrawLine(aRect.x0, (aRect.y1 + 19 + 16) / 2, aRect.x1, (aRect.y1 + 19 + 16) / 2);
		break;
	default:
		return LISTWHEEL_OwnerDraw(pDrawItemInfo);
	}
	return 0;
}
/**
  * @brief 系统设置第二页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window2(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;
	GUI_RECT RECT_Setting_time_TEXT = { 20, 340, 550, 365 };
	unsigned char i;
	CALENDAR_DATE CALENDAR_Date;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		/* 文本控件初始化 */
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "系统日期和时间");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Time and Date");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_SetDate_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "设置系统日期");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Set Date");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_SetTime_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "设置系统时间");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Set Time");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		#if GUI_OPERATING > 0u
		/* 更新系统日期时间 */
		RTC_ReadClock();
		sprintf(System_Date, "%0.4d/%0.2d/%0.2d",
			g_tRTC.Year,
			g_tRTC.Mon,
			g_tRTC.Day);
		sprintf(System_Time_Display, "%0.2d:%0.2d:%0.2d",
			g_tRTC.Hour,
			g_tRTC.Min,
			g_tRTC.Sec);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Date_TEXT);
		#if GUI_OPERATING > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, System_Date);
		#else
			TEXT_SetText(hItem, "2023/01/01");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Time_TEXT);
		#if GUI_OPERATING > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, System_Time_Display);
		#else
			TEXT_SetText(hItem, "12:00:00");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Week_TEXT);
		#if GUI_OPERATING > 0u
			TEXT_SetText(hItem, apWeek[g_tRTC.Week - 1]);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Sunday");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化按键控件 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_SetDate_BUTTON);              //获取编辑框句柄
		#if GUI_LANGUAGE > 0u
			BUTTON_SetFont(hItem, &GUI_FontHZ24);                               
			BUTTON_SetText(hItem, "设置系统日期");                                   
		#else
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);                              
			BUTTON_SetText(hItem, "Set Date");                                    
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_SetTime_BUTTON);              //获取编辑框句柄
		#if GUI_LANGUAGE > 0u
			BUTTON_SetFont(hItem, &GUI_FontHZ24);                                
			BUTTON_SetText(hItem, "设置系统时间");                                  
		#else
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);                            
			BUTTON_SetText(hItem, "Set Time");                                
		#endif
		#if GUI_OPERATING > 0u
			/* 日历控件初始化 */
			CALENDAR_SetDefaultSize(CALENDAR_SI_HEADER, 30);
			CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_X, 40);
			CALENDAR_SetDefaultSize(CALENDAR_SI_CELL_Y, 30);
			#if GUI_LANGUAGE > 0u
				CALENDAR_SetDefaultDays(apDays);
				CALENDAR_SetDefaultMonths(apMonths);
				CALENDAR_SetDefaultFont(CALENDAR_FI_CONTENT, &GUI_FontHZ24);
				CALENDAR_SetDefaultFont(CALENDAR_FI_HEADER, &GUI_FontHZ24);
			#else
				CALENDAR_SetDefaultFont(CALENDAR_FI_CONTENT, GUI_FONT_24B_1);
				CALENDAR_SetDefaultFont(CALENDAR_FI_HEADER, GUI_FONT_24B_1);
			#endif
			CALENDAR_SetDefaultBkColor(CALENDAR_CI_WEEKDAY, GUI_WHITE);               //设置日历颜色
			CALENDAR_SetDefaultBkColor(CALENDAR_CI_WEEKEND, GUI_WHITE);
			CALENDAR_SetDefaultBkColor(CALENDAR_CI_SEL, GUI_BLUE);
			CALENDAR_SetDefaultBkColor(CALENDAR_CI_HEADER, GUI_LIGHTBLUE);
			/* 在指定位置创建CALENDAR控件 */
			CALENDAR_Create(hWin,                     /* 父窗口句柄 */
				10,                                   /* 相对于父窗口坐标的最左像素 */
				70,                                   /* 相对于父窗口坐标的最上像素 */
				g_tRTC.Year,                          /* 起始年份 */
				g_tRTC.Mon,							  /* 起始月份 */
				g_tRTC.Day,							  /* 起始日期 */
				2,                                    /* 每周起始星期 */
				ID_APP_Settings_CALENDAR,             /* 控件ID */
				WM_CF_SHOW);                          /* 窗口创建标志*/
		#endif
		/* 初始化LISTWHEEL */
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetHour_LISTWHEEL);        //获取滚轮句柄
		LISTWHEEL_SetLineHeight(hItem, 30);
		LISTWHEEL_SetSnapPosition(hItem, (240 - 30) / 2);
		LISTWHEEL_SetFont(hItem, GUI_FONT_24B_ASCII);
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
		LISTWHEEL_SetDeceleration(hItem, 30);
		LISTWHEEL_SetOwnerDraw(hItem, Time_Setting_ListwheelDraw);
		LISTWHEEL_SetSel(hItem, 0);
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetMinute_LISTWHEEL);       //获取滚轮句柄
		LISTWHEEL_SetLineHeight(hItem, 30);
		LISTWHEEL_SetSnapPosition(hItem, (240 - 30) / 2);
		LISTWHEEL_SetFont(hItem, GUI_FONT_24B_ASCII);
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
		LISTWHEEL_SetDeceleration(hItem, 30);
		LISTWHEEL_SetOwnerDraw(hItem, Time_Setting_ListwheelDraw);
		LISTWHEEL_SetSel(hItem, 0);
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetSecond_LISTWHEEL);       //获取滚轮句柄
		LISTWHEEL_SetLineHeight(hItem, 30);
		LISTWHEEL_SetSnapPosition(hItem, (240 - 30) / 2);
		LISTWHEEL_SetFont(hItem, GUI_FONT_24B_ASCII);
		LISTWHEEL_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_UNSEL, 0x191919);
		LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
		LISTWHEEL_SetDeceleration(hItem, 30);
		LISTWHEEL_SetOwnerDraw(hItem, Time_Setting_ListwheelDraw);
		LISTWHEEL_SetSel(hItem, 0);
		/* 添加LISTWHEEL0文本项 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetHour_LISTWHEEL);
		for (i = 0; i < GUI_COUNTOF(_ap_sethour); i++)
		{
			LISTWHEEL_AddString(hItem, *(_ap_sethour + i));
		}
		/* 添加LISTWHEEL1文本项 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetMinute_LISTWHEEL);
		for (i = 0; i < GUI_COUNTOF(_ap_setminute); i++)
		{
			LISTWHEEL_AddString(hItem, *(_ap_setminute + i));
		}
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_SetSecond_LISTWHEEL);
		for (i = 0; i < GUI_COUNTOF(_ap_setsecond); i++)
		{
			LISTWHEEL_AddString(hItem, *(_ap_setsecond + i));
		}
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					//清屏
		GUI_DrawGradientH(0, 0, 600, 440, GUI_LIGHTCYAN, GUI_LIGHTMAGENTA);
		GUI_SetColor(GUI_BLACK);
		GUI_DrawRect(8, 68, 291, 311);
		GUI_DrawRect(9, 69, 292, 312);
		GUI_DrawRect(308, 68, 571, 311);
		GUI_DrawRect(309, 69, 572, 312);
		GUI_SetColor(GUI_LIGHTGRAY);
		GUI_FillRect(390,70,400,310);
		GUI_FillRect(480, 70, 490, 310);
		GUI_SetColor(GUI_BLACK);
		GUI_DrawLine(390, 172, 400, 172);
		GUI_DrawLine(390, 207, 400, 207);
		GUI_DrawLine(480, 172, 490, 172);
		GUI_DrawLine(480, 207, 490, 207);
		GUI_DrawLine(395, 70, 395, 310);
		GUI_DrawLine(485, 70, 485, 310);
		#if GUI_OPERATING > 0u
			/* 更新系统日期时间 */
			RTC_ReadClock();
			sprintf(System_Date, "%0.4d/%0.2d/%0.2d",
				g_tRTC.Year,
				g_tRTC.Mon,
				g_tRTC.Day);
			sprintf(System_Time_Display, "%0.2d:%0.2d:%0.2d",
				g_tRTC.Hour,
				g_tRTC.Min,
				g_tRTC.Sec);
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Date_TEXT);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, System_Date);
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Time_TEXT);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, System_Time_Display);
			hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window2_Week_TEXT);
			TEXT_SetText(hItem, apWeek[g_tRTC.Week - 1]);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#endif
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件ID */
		Id = WM_GetId(pMsg->hWinSrc);
		/* 获取通知代码 */
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_APP_Settings_SetHour_LISTWHEEL:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetHour_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetHour_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
				U8 index = LISTWHEEL_GetPos(hItem);
				LISTWHEEL_SetSel(hItem, index);
				break;
			}
			break;
		case ID_APP_Settings_SetMinute_LISTWHEEL:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetMinute_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetMinute_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
				U8 index = LISTWHEEL_GetPos(hItem);
				LISTWHEEL_SetSel(hItem, index);
				break;
			}
			break;
		case ID_APP_Settings_SetSecond_LISTWHEEL:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetSecond_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x191919);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Settings_SetSecond_LISTWHEEL);
				LISTWHEEL_SetTextColor(hItem, LISTWHEEL_CI_SEL, 0x007dfe);
				U8 index = LISTWHEEL_GetPos(hItem);
				LISTWHEEL_SetSel(hItem, index);
				break;
			}
			break;
		case ID_APP_Settings_Window2_SetDate_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (Time_modify_enabled_bit == System_Time_Modify_Enable)
				{
					CALENDAR_GetSel(WM_GetDialogItem(hWin, ID_APP_Settings_CALENDAR), &CALENDAR_Date);
					#if GUI_OPERATING > 0u
						//printf("读取日期:%0.4d/%0.2d/%0.2d\n\r",CALENDAR_Date.Year, CALENDAR_Date.Month, CALENDAR_Date.Day);
						//printf("读取时间:%02d:%0.2d:%0.2d\n\r",g_tRTC.Hour, g_tRTC.Min, g_tRTC.Sec);
						g_tRTC.Year = CALENDAR_Date.Year;
						g_tRTC.Mon = CALENDAR_Date.Month;
						g_tRTC.Day = CALENDAR_Date.Day;
						RTC_WriteClock(g_tRTC.Year, g_tRTC.Mon, g_tRTC.Day, g_tRTC.Hour, g_tRTC.Min, g_tRTC.Sec);
						//WM_Paint(hAPP_Settings_CurrentPage);
						WM_InvalidateRect(hWin, &RECT_Setting_time_TEXT);
					#endif
				}
				break;
			}
			break;
		case ID_APP_Settings_Window2_SetTime_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (Time_modify_enabled_bit == System_Time_Modify_Enable)
				{
					#if GUI_OPERATING > 0u
						g_tRTC.Hour = LISTWHEEL_GetSel(WM_GetDialogItem(hWin, ID_APP_Settings_SetHour_LISTWHEEL));
						g_tRTC.Min = LISTWHEEL_GetSel(WM_GetDialogItem(hWin, ID_APP_Settings_SetMinute_LISTWHEEL));
						g_tRTC.Sec = LISTWHEEL_GetSel(WM_GetDialogItem(hWin, ID_APP_Settings_SetSecond_LISTWHEEL));
						//printf("读取日期:%0.4d/%0.2d/%0.2d\n\r",CALENDAR_Date.Year, CALENDAR_Date.Month, CALENDAR_Date.Day);
						//printf("读取时间:%02d:%0.2d:%0.2d\n\r",g_tRTC.Hour, g_tRTC.Min, g_tRTC.Sec);
						RTC_WriteClock(g_tRTC.Year, g_tRTC.Mon, g_tRTC.Day, g_tRTC.Hour, g_tRTC.Min, g_tRTC.Sec);
						WM_InvalidateRect(hWin, &RECT_Setting_time_TEXT);
					#endif
				}
				break;
			}
			break;
		}
		break;

	case WM_TIMER:
		WM_InvalidateRect(hWin, &RECT_Setting_time_TEXT);
		WM_RestartTimer(pMsg->Data.v, 1000);
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第三页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window3(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window3_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "无线网络连接");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Wi-Fi Connection");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		break;

	case WM_NOTIFY_PARENT:
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第四页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window4(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window4_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "蓝牙连接");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Bluetooth Connection");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		break;

	case WM_NOTIFY_PARENT:
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第五页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window5(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;
	GUI_RECT rBackground_bmp = { 100, 70, 500, 310 };
	
	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window5_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "桌面背景设置");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Desktop Background Settings");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window5_Next_BUTTON);
		#if GUI_LANGUAGE > 0u
			BUTTON_SetText(hItem, "下一个");
			BUTTON_SetFont(hItem, &GUI_FontHZ24);
		#else
			BUTTON_SetText(hItem, "Next");
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window5_Previous_BUTTON);
		#if GUI_LANGUAGE > 0u
			BUTTON_SetText(hItem, "上一个");
			BUTTON_SetFont(hItem, &GUI_FontHZ24);
		#else
			BUTTON_SetText(hItem, "Previous");
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window5_SetBackground_BUTTON);
		#if GUI_LANGUAGE > 0u
			BUTTON_SetText(hItem, "设置桌面背景");
			BUTTON_SetFont(hItem, &GUI_FontHZ24);
		#else
			BUTTON_SetText(hItem, "Set Background");
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					                  //清屏
		GUI_SetColor(GUI_BLACK);
		GUI_DrawRect(98, 68, 502, 312);
		GUI_DrawRect(99, 69, 501, 311);
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件 ID */
		Id = WM_GetId(pMsg->hWinSrc);

		/* 获取消息内容 */
		NCode = pMsg->Data.v;

		switch (Id)
		{
		case ID_APP_Settings_Window5_Next_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				WM_InvalidateRect(hWin, &rBackground_bmp);
				GUI_SetColor(GUI_WHITE);
				GUI_FillRect(100, 70, 500, 310 );
				break;
			}
			break;
		case ID_APP_Settings_Window5_Previous_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				WM_InvalidateRect(hWin, &rBackground_bmp);
				GUI_SetColor(GUI_WHITE);
				GUI_FillRect(100, 70, 500, 310 );
			}
			break;
		case ID_APP_Settings_Window5_SetBackground_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		}
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第六页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window6(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window6_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "音量设置");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "volume Settings");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		break;

	case WM_NOTIFY_PARENT:
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第七页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window7(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "内存管理");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "Memory Management");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMIN_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "内部SRAM");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SRAMIN");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMEX_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "外部SRAM");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SRAMEX");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMCCM_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "CCMSRAM");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "CCMSRAM");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SDIO_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "SD储存卡");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SDIO");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMIN_TOT_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "共20KB");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SRAMIN:20KB");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMEX_TOT_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "共800KB");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SRAMEX:800KB");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMCCM_TOT_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "共60KB");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SRAMCCM:60KB");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SDIO_TOT_TEXT);
#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "共29.7GB");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		TEXT_SetText(hItem, "SDIO:29.7GB");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMIN_FRE_TEXT);
#if GUI_LANGUAGE > 0u
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMEX_FRE_TEXT);
#if GUI_LANGUAGE > 0u
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMCCM_FRE_TEXT);
#if GUI_LANGUAGE > 0u
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SDIO_FRE_TEXT);
#if GUI_LANGUAGE > 0u
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
		//TEXT_SetText(hItem, str_free_size);
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
        hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMIN_PROGBAR);
		PROGBAR_SetFont(hItem, GUI_FONT_24B_1);
		PROGBAR_SetMinMax(hItem, 0, 200);            //20KB
#if		GUI_OPERATING > 0u
		//PROGBAR_SetValue(hItem,20*mem_perused(SRAMIN)/10);
#else
		PROGBAR_SetValue(hItem, 20 * 41 / 10);
#endif
		PROGBAR_SetBarColor(hItem,0,GUI_GREEN);
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMEX_PROGBAR);
		PROGBAR_SetFont(hItem, GUI_FONT_24B_1);
		PROGBAR_SetMinMax(hItem, 0, 8000);           //800KB
#if		GUI_OPERATING > 0u
		//PROGBAR_SetValue(hItem, 800 * mem_perused(SRAMEX) / 10);
#else
		PROGBAR_SetValue(hItem, 800 * 57 / 10);
#endif
		PROGBAR_SetBarColor(hItem,0,GUI_GREEN);
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SRAMCCM_PROGBAR);
		PROGBAR_SetFont(hItem, GUI_FONT_24B_1);
		PROGBAR_SetMinMax(hItem, 0, 600);           //60KB
#if		GUI_OPERATING > 0u
		//PROGBAR_SetValue(hItem, 60 * mem_perused(SRAMCCM) / 10);
#else
		PROGBAR_SetValue(hItem, 60 * 29 / 10);
#endif
		PROGBAR_SetBarColor(hItem,0,GUI_GREEN);
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window7_SDIO_PROGBAR);
		PROGBAR_SetFont(hItem, GUI_FONT_24B_1);
		PROGBAR_SetMinMax(hItem, 0, 320);           //32GB
#if		GUI_OPERATING > 0u
		//PROGBAR_SetValue(hItem, 320 * ((float)1 - ((float)FRE_SIZE / (float)TOT_SIZE)));
#else
		PROGBAR_SetValue(hItem, 32 * 3 / 10);
#endif
		PROGBAR_SetBarColor(hItem,0,GUI_GREEN);

		break;

	case WM_PAINT:
		GUI_DrawGradientV(0, 0, 600, 480, GUI_WHITE, GUI_LIGHTBLUE);
		GUI_DrawGradientH(0, 65, 450, 70, GUI_RED, GUI_YELLOW);
		GUI_DrawGradientH(0, 165, 450, 170, GUI_RED, GUI_YELLOW);
		GUI_DrawGradientH(0, 265, 450, 270, GUI_RED, GUI_YELLOW);
		GUI_DrawGradientH(0, 365, 450, 370, GUI_RED, GUI_YELLOW);
		break;
	
	case WM_NOTIFY_PARENT:
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/**
  * @brief 系统设置第八页回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Settings_Window8(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;

	(void)NCode;        //空指针
	(void)Id;           //空指针
	(void)hItem;

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		hItem = WM_GetDialogItem(hWin, ID_APP_Settings_Window8_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetText(hItem, "电池管理");
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetText(hItem, "Battery Management");
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		break;

	case WM_NOTIFY_PARENT:
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */

/************************************************************************************************************************
*
*       公共代码
*
*************************************************************************************************************************
*/
/**
  * @brief 系统设置APP窗口创建函数
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Create(void)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Create, GUI_COUNTOF(Dialog_APP_Settings_Create), _cbAPP_Settings, WM_HBKWIN, 0, 0);
	return hWin;
}

/**
  * @brief 系统设置第一页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window1_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page1_Create, GUI_COUNTOF(Dialog_APP_Settings_Page1_Create), _cbAPP_Settings_Window1, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第二页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window2_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	WM_HWIN hTimer;
	(void)hTimer;    //空指针
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page2_Create, GUI_COUNTOF(Dialog_APP_Settings_Page2_Create), _cbAPP_Settings_Window2, hParents, 0, 0);
	hTimer = WM_CreateTimer(WM_GetClientWindow(hWin), 0, 1000, 0);       //创建定时器
	return hWin;
}
/**
  * @brief 系统设置第三页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window3_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page3_Create, GUI_COUNTOF(Dialog_APP_Settings_Page3_Create), _cbAPP_Settings_Window3, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第四页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window4_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page4_Create, GUI_COUNTOF(Dialog_APP_Settings_Page4_Create), _cbAPP_Settings_Window4, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第五页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window5_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page5_Create, GUI_COUNTOF(Dialog_APP_Settings_Page5_Create), _cbAPP_Settings_Window5, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第六页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window6_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page6_Create, GUI_COUNTOF(Dialog_APP_Settings_Page6_Create), _cbAPP_Settings_Window6, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第七页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window7_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page7_Create, GUI_COUNTOF(Dialog_APP_Settings_Page7_Create), _cbAPP_Settings_Window7, hParents, 0, 0);
	return hWin;
}
/**
  * @brief 系统设置第八页
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Settings_Window8_Create(WM_HWIN hParents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_APP_Settings_Page8_Create, GUI_COUNTOF(Dialog_APP_Settings_Page8_Create), _cbAPP_Settings_Window8, hParents, 0, 0);
	return hWin;
}
/*************************** End of file ****************************/
