/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

/*------------------------------------------------  智能小汪GUI   -----------------------------------------------------*/

#include <stddef.h>
#include <string.h>
#include "GUI_Main.h"
#include "GUI_Camera_DLG.h"
#include "GUI_Clock_DLG.h"
#include "GUI_Calendar_DLG.h"
#include "GUI_Music_DLG.h"
#include "GUI_Setting_DLG.h"
#include "GUI_Picture_DLG.h"
#include "GUI_DrawingBoard_DLG.h"
#include "GUI_Oscilloscope_DLG.h"
#if GUI_OPERATING > 0u
	#include "includes.h"
#endif

/************************************************************************************************************************
*
*       宏定义
*
*************************************************************************************************************************
*/
/* 显示屏大小宏定义 */
#define SCREEN_Width    800     /* 显示屏的宽度 */  
#define SCREEN_Height   480     /* 显示屏高度   */ 
/* 图标窗口相关宏定义 */
#define DesktopMotion_TBorder   40     /* 滑动页面的上边距 */
#define ICONVIEW_TBorder        30     /* 控件ICONVIEW的上边距 */
#define ICONVIEW_LBorder        70     /* 控件ICONVIEW的左边距 */  
#define ICONVIEW_Width          680    /* 控件ICONVIEW的宽 */  
#define ICONVIEW_Height         238    /* 控件ICONVIEW的高 */  
#define ICONVIEW_YSpace         10     /* 控件ICONVIEW的Y方向间距 */
#define ICONVIEW_XSpace         10     /* 控件ICONVIEW的Y方向间距 */
#define ICON_Width              100    /* 控件ICONVIEW的图标的宽度 */  
#define ICON_Height             114    /* 控件ICONVIEW的图标的高度, 含图标下面的文本，一起的高度 */ 

/************************************************************************************************************************
*
*       变量声明
*
*************************************************************************************************************************
*/
char System_Date[11];                 //系统日期
char System_Time[6];                  //系统时间
char System_Date_Display[15];         //xxxx年xx月xx日
char System_Time_Display[9];          //xx:xx:xx

typedef struct        //图标结构体
{
	const GUI_BITMAP* pBitmap;
	const char* pTextEn;
	const char* pTextCn;
} IconView_ITEM;

typedef struct       //坐标结构体
{
	int xPos;
	int yPos;
	int Index;
} ITEM_INFO;

typedef struct
{
	int          Pos;
	int          FinalMove;
	ITEM_INFO* pItemInfo;
} PARA;

/* 桌面句柄声明 */
WM_HWIN hDesktopMotion;    //桌面滑动窗口句柄
WM_HWIN hDesktopTimer;     //桌面定时器句柄
GUI_HMEM hMemBackground;   //背景图片存储空间
/* 应用窗口句柄声明 */
WM_HWIN hWinComputerTask;       //我的电脑APP窗口句柄
WM_HWIN hWinSettingsTask;       //系统设置APP窗口句柄
WM_HWIN hWinCameraTask;         //照相机APP窗口句柄
WM_HWIN hWinClockTask;          //电子时钟APP窗口句柄
WM_HWIN hWinCalenderTask;       //万年历APP窗口句柄
WM_HWIN hWinMusicTask;          //音乐播放APP窗口句柄
WM_HWIN hWinPictureTask;        //图片浏览APP窗口句柄
WM_HWIN hWinDrawingBoardTask;   //绘画板APP窗口句柄
WM_HWIN hWinOscilloscopeTask;   //示波器APP窗口句柄
WM_HWIN hWinReservedTask;       //预留APP窗口句柄
/************************************************************************************************************************
*
*       外部变量声明
*
*************************************************************************************************************************
*/
extern unsigned char Background_enabled_bit;               //桌面背景启用标志位
extern unsigned char Time_modify_enabled_bit;              //系统时间修改标志位
extern unsigned char Voice_Broadcast_enabled_bit;          //系统语音播报标志位
/************************************************************************************************************************
*
*       静态变量声明
*
*************************************************************************************************************************
*/
/* 桌面图标数组 */
/* 用于第一屏桌面上ICONVIEW图标的创建 */
static const IconView_ITEM _aBitmapItem1[] =
{
	{&bmmycomputer,      "Computer",       "我的电脑"},
	{&bmsetting,         "Settings",       "系统设置"},
	{&bmfolder,          "Folder",         "文件夹"},
	{&bmpicture,         "Picture",        "图片浏览"},
	{&bmvideo,           "Video",          "视频浏览"},
	{&bmcamera,          "Camera",         "照相机"},

	{&bmnews,            "News",           "新闻浏览"},
	{&bmclock,           "Clock",          "电子时钟"},
	{&bmcalendar,        "Calendar",       "万年历"},
	{&bmmusic,           "Music",          "音乐播放"},
	{&bmrecorder,        "Recorder",       "录音机"},
	{&bmradio,           "Radio",          "收音机"},
};
/* 用于第二屏桌面上ICONVIEW图标的创建 */
static const IconView_ITEM _aBitmapItem2[] =
{
	{&bmcodedlock,      "Coded lock",      "密码锁"},
	{&bmcontrol,        "Control",         "控制台"},
	{&bmdrawingboard,   "Board",           "绘画板"},
	{&bmusb,            "USB",             "U盘"},
	{&bmgame,           "Game",            "游戏"},
	{&bmgps,            "GPS",             "GPS定位"},

	{&bmoscilloscope,   "Oscilloscope",    "示波器"},
};
/* 用于第三屏桌面上ICONVIEW图标的创建(暂时未用到第三页) */

/* 用于第一屏桌面上图标窗口句柄声明 */
static WM_HWIN *_aphWin0[] =
{
	&hWinComputerTask,
	&hWinSettingsTask,
	&hWinReservedTask,
	&hWinPictureTask,
	&hWinReservedTask,
	&hWinCameraTask,

	&hWinReservedTask,
	&hWinClockTask,
	&hWinCalenderTask,
	&hWinMusicTask,
	&hWinReservedTask,
	&hWinReservedTask,
};

/* 用于第二屏桌面上图标窗口句柄声明 */
static WM_HWIN *_aphWin1[] =
{
	&hWinComputerTask,
	&hWinReservedTask,
	& hWinDrawingBoardTask,
	&hWinReservedTask,
	&hWinReservedTask,
	&hWinReservedTask,

	&hWinOscilloscopeTask,
};

static WM_HWIN hIcon1, hIcon2;      //图标控件句柄
static uint8_t s_ucIconSwitch = 0;  //滑动图标页数

/************************************************************************************************************************
*
*       应用程序入口函数
*
*************************************************************************************************************************
*/
static WM_HWIN (*_apModules0[])(void) =
{
	FUN_APP_Reserved_Create,
	FUN_APP_Settings_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_Picture_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_Camera_Create,

	FUN_APP_Reserved_Create,
	FUN_APP_Clock_Create,
	FUN_APP_Calender_Create,
	FUN_APP_Music_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_Reserved_Create,
};

static WM_HWIN (*_apModules1[])(void) =
{
	FUN_APP_Reserved_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_DrawingBoard_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_Reserved_Create,
	FUN_APP_Reserved_Create,

	FUN_APP_Oscilloscope_Create,
};

/************************************************************************************************************************
*
*       静态代码
*
*************************************************************************************************************************
*/

/* emwin初始化 */
/**
  * @brief GUI初始化
  * @note 无
  * @param 无
  * @retval 无
  */
static void Fun_GUI_SystemInit(void)
{
	/* 初始化 */
	GUI_Init();

	/*
	 关于多缓冲和窗口内存设备的设置说明
	   1. 使能多缓冲是调用的如下函数，用户要在LCDConf_Lin_Template.c文件中配置了多缓冲，调用此函数才有效：
		  WM_MULTIBUF_Enable(1);
	   2. 窗口使能使用内存设备是调用函数：WM_SetCreateFlags(WM_CF_MEMDEV);
	   3. 如果emWin的配置多缓冲和窗口内存设备都支持，二选一即可，且务必优先选择使用多缓冲，实际使用
		  STM32H7 + 32位SDRAM + RGB565/RGB888平台测试，多缓冲可以有效的降低窗口移动或者滑动时的撕裂
		  感，并有效的提高流畅性，通过使能窗口使用内存设备是做不到的。
	   4. 所有emWin例子默认是开启三缓冲。
	*/
	WM_MULTIBUF_Enable(1);
	//GUI_EnableAlpha(1);
	/*
	   触摸校准函数默认是注释掉的，电阻屏需要校准，电容屏无需校准。如果用户需要校准电阻屏的话，执行
	   此函数即可，会将触摸校准参数保存到EEPROM里面，以后系统上电会自动从EEPROM里面加载。
	   TOUCH_Calibration(2); 参数为2表示两点校准
	   TOUCH_Calibration(4); 参数为4表示四点校准
	*/

	WM_MOTION_Enable(1);    /* 使能滑动 */
	/*
	默认是500ms，这里将其修改为50ms，这个参数一定程度上决定的灵敏度，能决定灵敏度.
	*/
	WM_MOTION_SetDefaultPeriod(20);

	/* 屏幕显示后点亮，有效防止瞬间高亮 */
	GUI_Delay(100);
	#if GUI_OPERATING > 0u
		LCD_SetBackLight(255);
	#endif

	/* 设置桌面窗口的背景色是白色，并且支持重绘 */
	WM_SetDesktopColor(GUI_WHITE);
	GUI_SetBkColor(GUI_WHITE);
}
/* function end */

/* 开机界面绘制 */
#if 0    // 0则跳过系统加载页面
	#define LineCap         28      /* 启动界面行间距 */
	#define delay_time      100     /* 启动界面延时时间ms*/
	/**
	  * @brief GUI加载界面
	  * @note 无
	  * @param 无
	  * @retval 无
	  */
	static void Fun_Loading_interface(void)
	{
		uint16_t usY = 40;
		#if GUI_OPERATING > 0u
			GUI_SetFont(&GUI_FontHZ24);
			GUI_SetColor(GUI_BLACK);
			GUI_Delay(delay_time);
			GUI_DispStringAt("***********************************************************************************", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("Welcome to Smart Dog", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   Hardware:        STM32-V7 armfly", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   uC/OS-III        V3.08.00", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   emWin        V6.16", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   FatFs        R0.12c", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("	 Copyright (C)2016-2020 armfly", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("***********************************************************************************", 0, usY);
			usY += 20;
			GUI_DispStringAt("系统加载中，请稍等......", 0, usY);
		#else
			GUI_SetFont(GUI_FONT_24B_1);
			GUI_SetColor(GUI_BLACK);
			GUI_Delay(delay_time);
			GUI_DispStringAt("***********************************************************************************", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("Welcome to Smart Dog", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   Hardware:        STM32-V7 armfly", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   uC/OS-III        V3.08.00", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   emWin        V6.16", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("   FatFs        R0.12c", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("	 Copyright (C)2016-2020 armfly", 0, usY);
			usY += LineCap;
			GUI_Delay(delay_time);
			GUI_DispStringAt("***********************************************************************************", 0, usY);
			usY += 30;
			GUI_Delay(delay_time);
			GUI_DispStringAt("The system is loading. Please wait for ......", 0, usY);
		#endif
		GUI_Delay(500);
	}
	#undef LineCap
	#undef delay_time
	 /* function end */
#endif

/**
  * @brief 桌面滑动窗口图标创建函数
  * @note 无
  * @param hParent父窗口  *pBm位图指针  BitmapNum位图数量  Id图标控件id  x最左像素（在父坐标中） y小工具的最上像素（在父坐标中） w水平尺寸（单位：像素） h垂直尺寸（单位：像素）
  * @retval 图标控件句柄
  */
static WM_HWIN _CreateICONVIEW(WM_HWIN hParent, const IconView_ITEM* pBm, int BitmapNum, int Id, int x, int y, int w, int h)
{
	WM_HWIN hIcon;
	int i;

	/*在指定位置创建指定尺寸的ICONVIEW 小工具*/
	hIcon = ICONVIEW_CreateEx(x, 					/* 小工具的最左像素（在父坐标中）*/
		y, 					/* 小工具的最上像素（在父坐标中）*/
		w,                     /* 小工具的水平尺寸（单位：像素）*/
		h, 	                /* 小工具的垂直尺寸（单位：像素）*/
		hParent, 				            /* 父窗口的句柄。如果为0 ，则新小工具将成为桌面（顶级窗口）的子窗口 */
		WM_CF_SHOW | WM_CF_HASTRANS,       /* 窗口创建标记。为使小工具立即可见，通常使用 WM_CF_SHOW */
		0,//ICONVIEW_CF_AUTOSCROLLBAR_V, 	/* 默认是0，如果不够现实可设置增减垂直滚动条 */
		Id, 			                    /* 小工具的窗口ID */
		ICON_Width, 				        /* 图标的水平尺寸 */
		ICON_Height);						/* 图标的垂直尺寸,图标和文件都包含在里面，不要大于ICONVIEW的高度，导致Text显示不完整*/


	/* 向ICONVIEW 小工具添加新图标 */
	for (i = 0; i < BitmapNum; i++)
	{
		#if GUI_LANGUAGE > 0u
			ICONVIEW_AddBitmapItem(hIcon, pBm[i].pBitmap, pBm[i].pTextCn);
		#else
			ICONVIEW_AddBitmapItem(hIcon, pBm[i].pBitmap, pBm[i].pTextEn);
		#endif
	}

	#if GUI_LANGUAGE > 0u
		ICONVIEW_SetFont(hIcon, &GUI_FontHZ24);
	#else
		ICONVIEW_SetFont(hIcon, GUI_FONT_24B_1);
	#endif
	/* 设置图标字体 */
	ICONVIEW_SetTextColor(hIcon, ICONVIEW_CI_UNSEL, GUI_BLACK);
	ICONVIEW_SetTextColor(hIcon, ICONVIEW_CI_SEL, GUI_BLACK);

	/* 设置图标字体对齐方式 */
	ICONVIEW_SetTextAlign(hIcon, GUI_TA_HCENTER | GUI_TA_BOTTOM);

	/* 设置图标选中时颜色 */
	ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_LIGHTCYAN);

	/* 设置小工具的背景色 32 位颜色值的前8 位可用于alpha混合处理效果*/
	//ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_WHITE | 0x80000000);

	/* 设置图标对齐方式 */
	ICONVIEW_SetIconAlign(hIcon, ICONVIEW_IA_HCENTER | ICONVIEW_IA_TOP);

	/* 设置X方向的边界值为0，默认不是0, Y方向默认是0，这里我们也进行一下设置，方便以后修改 */
	ICONVIEW_SetFrame(hIcon, GUI_COORD_X, 0);
	ICONVIEW_SetFrame(hIcon, GUI_COORD_Y, 0);

	/* 设置图标在x 或y 方向上的间距。*/
	ICONVIEW_SetSpace(hIcon, GUI_COORD_X, ICONVIEW_XSpace);
	ICONVIEW_SetSpace(hIcon, GUI_COORD_Y, ICONVIEW_YSpace);

	/* 设置对齐方式 在5.22版本中最新加入的 */
	ICONVIEW_SetIconAlign(hIcon, ICONVIEW_IA_HCENTER | ICONVIEW_IA_TOP);
	//ICONVIEW_SetTextColor(hIcon, ICONVIEW_CI_UNSEL, 0xF020A0);
	return hIcon;
}
/*------------------------------------------------------------------------------------------*/
/*-------------------------------------  回调函数   ----------------------------------------*/
/*------------------------------------------------------------------------------------------*/
/**
  * @brief 桌面滑动窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbMotion(WM_MESSAGE* pMsg)
{
	WM_MOTION_INFO* pInfo;
	WM_HWIN          hWin = pMsg->hWin;
	PARA* pPara;
	static uint32_t  tStart, tEnd;
	int NCode, Id;

	switch (pMsg->MsgId)
	{
	case WM_PRE_PAINT:
		GUI_MULTIBUF_Begin();
		break;

	case WM_POST_PAINT:
		GUI_MULTIBUF_End();
		break;

	case WM_NOTIFY_PARENT:
		Id = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch (Id)
		{
			/* 第一个界面上的图标 */
		case GUI_ID_ICONVIEW0:
			switch (NCode)
			{
				/* ICON控件点击消息 */
			case WM_NOTIFICATION_CLICKED:
				tStart = GUI_GetTime();
				break;

				/* ICON控件释放消息 */
			case WM_NOTIFICATION_RELEASED:
				tEnd = GUI_GetTime() - tStart;
				if (tEnd > 800)
				{
					WM_SetFocus(WM_HBKWIN);
					break;
				}
				*_aphWin0[ICONVIEW_GetSel(pMsg->hWinSrc)] = _apModules0[ICONVIEW_GetSel(pMsg->hWinSrc)]();
				break;
			}
			break;

			/* 第二个界面上的图标 */
		case GUI_ID_ICONVIEW1:
			switch (NCode)
			{
				/* ICON控件点击消息 */
			case WM_NOTIFICATION_CLICKED:
				tStart = GUI_GetTime();
				break;

				/* ICON控件释放消息 */
			case WM_NOTIFICATION_RELEASED:
				tEnd = GUI_GetTime() - tStart;
				if (tEnd > 800)
				{
					WM_SetFocus(WM_HBKWIN);
					break;
				}
				*_aphWin1[ICONVIEW_GetSel(pMsg->hWinSrc)] = _apModules1[ICONVIEW_GetSel(pMsg->hWinSrc)]();
				break;
			}
			break;

			/* 第三个界面上的图标，仅用于演示目的 */
		case GUI_ID_ICONVIEW2:
			switch (NCode)
			{
				/* ICON控件点击消息 */
			case WM_NOTIFICATION_CLICKED:
				tStart = GUI_GetTime();
				break;

				/* ICON控件释放消息 */
			case WM_NOTIFICATION_RELEASED:
				tEnd = GUI_GetTime() - tStart;
				if (tEnd > 800)
				{
					WM_SetFocus(WM_HBKWIN);
					break;
				}
				//_apModules2[ICONVIEW_GetSel(pMsg->hWinSrc)](WM_HBKWIN);
				break;
			}
			break;
		}
		break;

	case WM_MOTION:
		WM_GetUserData(hWin, &pPara, sizeof(pPara));
		pInfo = (WM_MOTION_INFO*)pMsg->Data.p;
		switch (pInfo->Cmd)
		{
		#if 1   /* H7板子采用的实现方式 ********************************
			   WM_MOTION_SetDefaultPeriod(20);周期设置小点，快速返回
			*/
			case WM_MOTION_INIT:
				pInfo->Flags = WM_CF_MOTION_X | WM_MOTION_MANAGE_BY_WINDOW;
				pInfo->SnapX = 1;
				break;

			case WM_MOTION_MOVE:
				pPara->FinalMove = pInfo->FinalMove;
				pPara->Pos += pInfo->dx;
				//printf_main("pData->xPos = %d %d\r\n", pPara->Pos, pInfo->dx);

				/* 滑动有加速度，停止后，减速度*/
				if (pPara->FinalMove)
				{
					//printf_main("pData->FinalMove = %d\r\n", pPara->Pos);
					/* 桌面图标移动到此范围内就将其固定在第3个图标显示 */
					if (pPara->Pos <= -(LCD_GetXSize() + LCD_GetXSize() / 2))
					{
						s_ucIconSwitch = 2;
						pPara->Pos = -(2 * LCD_GetXSize());
					}
					/* 桌面图标移动到此范围内就将其固定在第2个图标显示 */
					else if ((pPara->Pos > -(LCD_GetXSize() + LCD_GetXSize() / 2)) && (pPara->Pos <= -LCD_GetXSize() / 2))
					{
						s_ucIconSwitch = 1;
						pPara->Pos = -(LCD_GetXSize());
					}
					/* 桌面图标移动到此范围内就将其固定在第1个图标显示 */
					else if (pPara->Pos > -LCD_GetXSize() / 2)
					{
						s_ucIconSwitch = 0;
						pPara->Pos = 0;
					}
				}

				/* WM_MOTION_SetDefaultPeriod设置的周期30ms及其以下时dx跳动较大
				   建议取值35-50即可。
				*/
				if ((pInfo->dx < -4) || (pInfo->dx > 4) || (pPara->FinalMove))
					/* 移动桌面图标 */
					WM_MoveTo(hWin, pPara->Pos, DesktopMotion_TBorder);

		#else  /* emWin默认的Motion使用方案 ********************************
			 WM_MOTION_SetDefaultPeriod(100);设置的时间长点可以看出效果
			*/
			case WM_MOTION_INIT:
				pInfo->Flags = WM_CF_MOTION_X | WM_MOTION_MANAGE_BY_WINDOW;
				pInfo->SnapX = 800; /* 设置栅格大小 */
				break;

			case WM_MOTION_MOVE:
				pPara->FinalMove = pInfo->FinalMove;
				pPara->Pos += pInfo->dx;
				//printf_main("pData->xPos = %d %d\r\n", pPara->Pos, pInfo->dx);


				/* 设置滑动到最左侧时的处理办法，超过一半就不可以再滑动了，否则会滑动进行下一个栅格*/
				if (pPara->Pos >= LCD_GetXSize() / 2)
					pPara->Pos = LCD_GetXSize() / 2 - 1;

				/* 设置滑动到最右侧时的处理办法，超过一半就不可以再滑动了，否则会滑动进行下一个栅格*/
				if (pPara->Pos <= -(LCD_GetXSize() * 2 + LCD_GetXSize() / 2))
					pPara->Pos = -(LCD_GetXSize() * 2 + LCD_GetXSize() / 2 - 1);

				/* 滑动松手后，会按照WM_MOTION_SetDefaultPeriod设置的时间减速并停止到最近的栅格 */
				if (pPara->FinalMove)
				{
					//printf_main("pData->FinalMove = %d\r\n", pPara->Pos);
					/* 桌面图标移动到此范围内就将其固定在第3个图标显示 */
					if (pPara->Pos <= -(LCD_GetXSize() + LCD_GetXSize() / 2))
					{
						s_ucIconSwitch = 2;
					}
					/* 桌面图标移动到此范围内就将其固定在第2个图标显示 */
					else if ((pPara->Pos > -(LCD_GetXSize() + LCD_GetXSize() / 2)) && (pPara->Pos <= -LCD_GetXSize() / 2))
					{
						s_ucIconSwitch = 1;
					}
					/* 桌面图标移动到此范围内就将其固定在第1个图标显示 */
					else if (pPara->Pos > -LCD_GetXSize() / 2)
					{
						s_ucIconSwitch = 0;
					}
				}

				/* 移动桌面图标 */
				WM_MoveTo(hWin, pPara->Pos, DesktopMotion_TBorder);

				/* 下面这个三个未使用，当设置滑动窗口的大小是800*480时，可以仅拖动ICONVIEW控件即可
					当前是采用800*3宽度的界面大小，是拖动的ICONVIEW控件的父窗口。
				*/
				//WM_MoveTo(hIcon1, pPara->Pos + ICONVIEW_LBorder , ICONVIEW_TBorder);
				//WM_MoveTo(hIcon2, pPara->Pos + 800 + ICONVIEW_LBorder, ICONVIEW_TBorder);
				//WM_MoveTo(hIcon3, pPara->Pos + 1600 + ICONVIEW_LBorder, ICONVIEW_TBorder);
		#endif
			break;

		case WM_MOTION_GETPOS:
			pInfo->xPos = pPara->Pos;
			break;
		}
		break;
	}
}
/* function end */

extern uint8_t Background_enabled_bit;  //桌面背景启用标志位
/**
  * @brief 桌面窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbBkWindow(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	GUI_RECT rRTC={550, 0, 800, 40};
	int x, y;
	
	switch (pMsg->MsgId)
	{
	case WM_PRE_PAINT:
		GUI_MULTIBUF_Begin();
		break;
	
	case WM_POST_PAINT:
		GUI_MULTIBUF_End();
		break;
		
	case WM_PAINT:
		/* 清屏 */
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();
		#if GUI_OPERATING > 0u
			/* 重绘桌面背景 */
			if (Background_enabled_bit == Background_Enable)
			{
				GUI_MEMDEV_WriteAt(hMemBackground, 0, 0);
			}
			else
			{
				GUI_DrawGradientV(0, 40, 800, 480, GUI_WHITE, GUI_LIGHTCYAN);
			}
			GUI_DrawGradientH(0, 0, 800, 40, GUI_LIGHTCYAN, GUI_LIGHTMAGENTA);
			/* 更新系统日期时间 */
			RTC_ReadClock();
			sprintf(System_Date, "%0.4d/%0.2d/%0.2d",
				g_tRTC.Year,
				g_tRTC.Mon,
				g_tRTC.Day);
			sprintf(System_Time, "%0.2d:%0.2d",
				g_tRTC.Hour,
				g_tRTC.Min);
			hItem = WM_GetDialogItem(WM_HBKWIN, ID_DESKTOP_Date_TEXT);
			TEXT_SetText(hItem, System_Date);
			hItem = WM_GetDialogItem(WM_HBKWIN, ID_DESKTOP_Time_TEXT);
			TEXT_SetText(hItem, System_Time);
		#else
			if (Background_enabled_bit == Background_Gradient)
			{
				GUI_DrawGradientV(0, 40, 800, 480, GUI_WHITE, GUI_LIGHTCYAN);
			}
			GUI_DrawGradientH(0, 0, 800, 40, GUI_LIGHTCYAN, GUI_LIGHTMAGENTA);
		#endif
		/* 绘制下方图标页提示栏 */
		x = LCD_GetXSize() / 2 - 23;
		y = LCD_GetYSize() - 63;
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_FillCircle(x, y, 3);
		GUI_FillCircle(x + 20, y, 3);
		GUI_FillCircle(x + 40, y, 3);
		GUI_FillCircle(x + s_ucIconSwitch * 20, y, 5);
		break;
		
	case WM_TIMER:
		WM_InvalidateRect(WM_GetDesktopWindow(), &rRTC);
		WM_RestartTimer(pMsg->Data.v, 10000);
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */

/************************************************************************************************************************
*
*       公共代码
*
*************************************************************************************************************************
*/
void Fun_Delete_DesktopTimer(void)       //删除桌面定时器停止桌面重绘
{
	/* 删除桌面定时器 */
	WM_DeleteTimer(hDesktopTimer);
}

void Fun_Create_DesktopTimer(void)       //创建桌面定时器,开始桌面定期重绘
{
	/* 创建桌面定时器 */
	hDesktopTimer = WM_CreateTimer(WM_GetDesktopWindow(), 0, 500, 0);
}
/*------------------------------------------------------------------------------------------*/
/*-------------------------------------  GUI主任务  ----------------------------------------*/
/*------------------------------------------------------------------------------------------*/
/**
  * @brief GUI主任务
  * @note 无
  * @param 无
  * @retval 无
  */
void MainTask(void)
{
	WM_HWIN hWin;
	WM_HWIN hItem;
	PARA Para;
	PARA* pPara;

	(void) hWin;
	
	/* 数据初始化 */
	pPara = &Para;
	pPara->Pos = 0;
	
	/* ------------------------------- 0.emWin初始化 ------------------------------------*/
	Fun_GUI_SystemInit();

	/* ------------------------------ 1.系统加载界面 ------------------------------------*/
	#if 0    // 0则跳过系统加载页面
		Fun_Loading_interface();
	#endif
	GUI_SetBkColor(GUI_WHITE);   /* 清屏 */
    GUI_Clear();
	
	/* ------------------------- 2.绘制桌面窗口的背景图片 -------------------------------*/
	hMemBackground = GUI_MEMDEV_CreateFixed(0, 
	                                 0, 
	                                 800, 
	                                 480, 
									 GUI_MEMDEV_HASTRANS, 
									 GUI_MEMDEV_APILIST_16, 
									 GUICC_M565);
	#if GUI_OPERATING > 0u								 
		_DrawBMPasBackground("Background/xiaowang.bmp", 160, 0, hMemBackground);
	#endif	

	/* ----------------------------- 3.绘制图标窗口 ------------------------------------*/
	hDesktopMotion = WM_CreateWindowAsChild(0,
						DesktopMotion_TBorder,
						SCREEN_Width * 3,
						SCREEN_Height - 40,
						WM_HBKWIN,
						WM_CF_MOTION_X | WM_CF_SHOW | WM_CF_HASTRANS,
						_cbMotion,
						sizeof(pPara));

	WM_SetUserData(hDesktopMotion, &pPara, sizeof(pPara));

	/*-------------------------------  4.桌面图标绘制   ----------------------------------*/	
	/* 第1个界面图标 */
	hIcon1 = _CreateICONVIEW(hDesktopMotion,
				_aBitmapItem1,
				GUI_COUNTOF(_aBitmapItem1),
				GUI_ID_ICONVIEW0,
				ICONVIEW_LBorder,
				ICONVIEW_TBorder,
				ICONVIEW_Width,
				ICONVIEW_Height);

	/* 第2个界面图标 */
	hIcon2 = _CreateICONVIEW(hDesktopMotion,
				_aBitmapItem2,
				GUI_COUNTOF(_aBitmapItem2),
				GUI_ID_ICONVIEW1,
				SCREEN_Width + ICONVIEW_LBorder,
				ICONVIEW_TBorder,
				ICONVIEW_Width,
				ICONVIEW_Height);

	/* 防止警告，留待以后备用 */
	(void)hIcon1;
	(void)hIcon2;
	
	/*-------------------------------  5.桌面文本绘制   ----------------------------------*/	
	/* 在指定位置创建TEXT控件 */
	hItem = TEXT_CreateEx(300,                        /* 相对于父窗口坐标的最左像素 */
		10,                                           /* 相对于父窗口坐标的最上像素 */
		200,                                          /* 水平尺寸 */
		25,                                           /* 垂直尺寸 */
		WM_HBKWIN,                                    /* 父窗口句柄 */
		WM_CF_SHOW,                                   /* 窗口创建标志 */
		TEXT_CF_HCENTER,                              /* 文本对齐 */
		ID_DESKTOP_System_TEXT,                       /* 控件ID */
		"");                                          /* 文本指针 */
	TEXT_SetTextColor(hItem, GUI_WHITE);

	#if GUI_LANGUAGE > 0u
		TEXT_SetText(hItem, "欢迎使用智能小汪");
		TEXT_SetFont(hItem, &GUI_FontHZ24);
	#else
		TEXT_SetText(hItem, "Welcome to use");
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
	#endif	

	/* 更新系统日期时间 */
	#if GUI_OPERATING > 0u
		RTC_ReadClock();
		sprintf(System_Date, "%0.4d/%0.2d/%0.2d",
			g_tRTC.Year,
			g_tRTC.Mon,
			g_tRTC.Day);
		sprintf(System_Time, "%0.2d:%0.2d",
			g_tRTC.Hour,
			g_tRTC.Min);
	#endif
	/* 在指定位置创建TEXT控件 */
	hItem = TEXT_CreateEx(600,                      /* 相对于父窗口坐标的最左像素 */
		10,                                           /* 相对于父窗口坐标的最上像素 */
		150,                                          /* 水平尺寸 */
		25,                                           /* 垂直尺寸 */
		WM_HBKWIN,                                    /* 父窗口句柄 */
		WM_CF_SHOW,                                   /* 窗口创建标志 */
		TEXT_CF_LEFT,                                 /* 文本对齐 */
		ID_DESKTOP_Date_TEXT,                         /* 控件ID */
		System_Date);                                 /* 文本指针 */
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem,GUI_WHITE);
	/* 在指定位置创建TEXT控件 */
	hItem = TEXT_CreateEx(720,                      /* 相对于父窗口坐标的最左像素 */
		10,                                           /* 相对于父窗口坐标的最上像素 */
		150,                                          /* 水平尺寸 */
		25,                                           /* 垂直尺寸 */
		WM_HBKWIN,                                    /* 父窗口句柄 */
		WM_CF_SHOW,                                   /* 窗口创建标志 */
		TEXT_CF_LEFT,                                 /* 文本对齐 */
		ID_DESKTOP_Time_TEXT,                         /* 控件ID */
		System_Time);                                 /* 文本指针 */
		TEXT_SetFont(hItem, GUI_FONT_24B_1);
		TEXT_SetTextColor(hItem,GUI_WHITE);
	
	/*-------------------------------  7.桌面窗口运行   ----------------------------------*/	
	/* 重定向桌面窗口回调函数 */
	WM_SetCallback(WM_HBKWIN, _cbBkWindow);
	/* 创建桌面定时器 */
	Fun_Create_DesktopTimer();
	
	/*------  主页面循环   -----*/
	while (1)
	{
		GUI_Delay(5);
	}
}
/* maintask end */

/******************************************************* End of file ********************************************************/
