/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#include "GUI_Main.h"
#include "GUI_Oscilloscope_DLG.h"
#if GUI_OPERATING > 0u
	#include "includes.h"
#endif

/************************************************************************************************************************
*
*       变量声明
*
*************************************************************************************************************************
*/
/* APP窗口句柄 */
extern WM_HWIN hWinOscilloscopeTask;    //示波器APP窗口句柄
WM_HWIN hWinOscilloscope_Settings;		//示波器设置窗口句柄
/* 位图声明 */
extern GUI_CONST_STORAGE GUI_BITMAP bm_settings;
extern GUI_CONST_STORAGE GUI_BITMAP bmpause;
extern GUI_CONST_STORAGE GUI_BITMAP bmplay;
extern GUI_CONST_STORAGE GUI_BITMAP bmSwitch;
/* AD7606数据声明 */
#if GUI_OPERATING > 0U
	extern AD7606_VAR_T g_tAD7606;
	uint16_t *Channel_FIFO;  //从FIFO中读取ADC值
	float Channel_Data[8];    //转化为电压值
#endif
/* 示波器数据句柄 */
GRAPH_DATA_Handle hData[8];				//数据对象的句柄(8个通道)
GUI_COLOR Data_Color[8] = {GUI_BLUE, GUI_GREEN, GUI_RED, GUI_MAGENTA, GUI_ORANGE, GUI_DARKCYAN, GUI_DARKYELLOW, GUI_BROWN };		//数据曲线颜色
int16_t* data_channel_1;
/* 示波器标志位声明 */
static uint8_t Grid_Visible_bit = Grid_Visible;								//示波器显示区网格可见标志位
static uint8_t Grid_Type_bit = Grid_Dash;									//示波器显示区网格类型标志位
static uint8_t Oscilloscope_Status_bit = Oscilloscope_Running;				//示波器运行状态标志位
static uint8_t Oscilloscope_Range_bit = Range_5V;							//示波器量程标志位
static uint8_t Oscilloscope_Mode_bit = Normal_Mode;							//示波器工作模式标志位
static uint8_t Oscilloscope_Oversampling_bit = _NonOversampled;		//示波器过采样率标志位
/* AD7606过采样标识符 */
static const char* AD7606_SampleStr[] =
{
	"无过采样, 最高支持采样率200Ksps",
	"2倍过采样, 最高支持采样率100Ksps",
	"4倍过采样, 最高支持采样率50Ksps",
	"8倍过采样, 最高支持采样率25Ksps",
	"16倍过采样, 最高支持采样率12.5Ksps",
	"32倍过采样, 最高支持采样率6.25Ksps",
	"64倍过采样, 最高支持采样率3.125Ksps",
};
/* AD7606不同过采样配置支持的最高采样速度 */
static const uint32_t AD7606_SampleFreq[] =
{
	200000,  /* 无过采样最高采样率200Ksps  */
	100000,  /* 2倍过采样最高采样率100Ksps */
	50000,   /* 4倍过采样最高采样率50Ksps  */
	25000,   /* 8倍过采样最高采样率25Ksps  */
	12500,   /* 16倍过采样最高采样率12.5Ksps  */
	6250,    /* 32倍过采样最高采样率6.25Ksps  */
	3125,    /* 64倍过采样最高采样率3.125Ksps */
};
/* AD7606过采样率 */
static const uint8_t AD7606_Oversampling[] = { 2,4,8,16,32,64 };
/************************************************************************************************************************
*
*       静态代码
*
*************************************************************************************************************************
*/
/**
  * @brief 示波器——应用窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Oscilloscope(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	WM_HWIN hScrollbar;
	WM_HWIN hGraph;
	int NCode;
	int Id;
	GRAPH_SCALE_Handle hScale_x, hScale_y;
	GUI_RECT rOscilloscope = { Oscilloscope_COORDINATE_X, Oscilloscope_COORDINATE_Y - NEW_APP_BAR_HIGHT, Oscilloscope_WIDTH + Oscilloscope_COORDINATE_X, Oscilloscope_HIGHT - NEW_APP_BAR_HIGHT + Oscilloscope_COORDINATE_Y };
	GUI_RECT rData = { 140,60,270,290 };
	uint8_t i;
	char buf[10];

	(void)NCode;
	(void)Id;
	(void)hScale_x;

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
#if APP_Oscilloscope_WINDOW_DEFAULT > 0u
		/* app窗口初始化 */
		FRAMEWIN_SetBarColor(hWin, 1, NEW_APP_BAR_COLOR_ENALBE);                //窗口标题栏颜色
		FRAMEWIN_SetBarColor(hWin, 0, NEW_APP_BAR_COLOR_UNENALBE);
#if GUI_LANGUAGE > 0u
		FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);                                  //窗口文本字体
		FRAMEWIN_SetText(hWin, "示波器");                                     //窗口文本
#else
		FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
		FRAMEWIN_SetText(hWin, "Oscilloscope");                                      //窗口文本
#endif
		FRAMEWIN_SetTextAlign(hWin, NEW_APP_BAR_ALIGN);                         //标题栏文本对齐方式
		FRAMEWIN_SetTitleHeight(hWin, NEW_APP_BAR_HIGHT);

		/* 初始化窗口性质 */
		if (NEW_APP_CLOSEBUTTON > 0u)
		{
			FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
		}
		if (NEW_APP_ACTIVE > 0u)
		{
			FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
		}
#else
		/* 用户定义区 */
		/* 用户定义区结束 */
#endif
/* 创建示波器显示区  */
		hGraph = GRAPH_CreateEx(Oscilloscope_COORDINATE_X,				/* 小工具的最左像素（在父坐标中）*/
			Oscilloscope_COORDINATE_Y,							/* 小工具的最上像素（在父坐标中）*/
			Oscilloscope_WIDTH,									/* 小工具的水平尺寸（单位：像素）*/
			Oscilloscope_HIGHT,									/* 小工具的垂直尺寸（单位：像素）*/
			hWin,												/* 父窗口的句柄。如果为0 ，则新小工具将成为桌面（顶级窗口）的子窗口 */
			WM_CF_SHOW,											/* 窗口创建标记。为使小工具立即可见，通常使用 WM_CF_SHOW */
			0,													/* 额外标志位,默认是0 */
			ID_APP_Oscilloscope_GRAPH);							/* 小工具的窗口ID */
		/* 设置示波器显示区边框 */
		GRAPH_SetBorder(hGraph, Oscilloscope_BorderL, Oscilloscope_BorderT, Oscilloscope_BorderR, Oscilloscope_BorderB);
		/* 设置示波器显示区颜色 */
		GRAPH_SetColor(hGraph, GUI_WHITE, GRAPH_CI_BK);
		GRAPH_SetColor(hGraph, GUI_LIGHTGRAY, GRAPH_CI_BORDER);
		GRAPH_SetColor(hGraph, GUI_BLACK, GRAPH_CI_GRID);
		GRAPH_SetColor(hGraph, GUI_BLACK, GRAPH_CI_FRAME);
		/* 固定X轴的栅格 */
		GRAPH_SetGridFixedX(hGraph, 1);
		/* 设置示波器显示区滚动栏 */
		//GRAPH_SetAutoScrollbar(hGraph, GUI_COORD_X, 1);
		//GRAPH_SetAutoScrollbar(hGraph, GUI_COORD_Y, 1);
		hScrollbar = SCROLLBAR_CreateAttached(hGraph, 0);
		SCROLLBAR_SetWidth(hScrollbar, Oscilloscope_ScrollbarWdith);
		hScrollbar = SCROLLBAR_CreateAttached(hGraph, SCROLLBAR_CF_VERTICAL);
		SCROLLBAR_SetWidth(hScrollbar, Oscilloscope_ScrollbarWdith);
		SCROLLBAR_SetValue(hScrollbar, Oscilloscope_ScaleSizeY/2);
		/* 设置示波器显示区网格 */
		GRAPH_SetGridVis(hGraph, Grid_Visible_bit);
		GRAPH_SetLineStyleH(hGraph, GUI_LS_DASH);
		GRAPH_SetLineStyleV(hGraph, GUI_LS_DASH);
		GRAPH_SetGridDistX(hGraph, Oscilloscope_GridDistX);
		GRAPH_SetGridDistY(hGraph, Oscilloscope_GridDistY);
		/* 设置示波器显示区网格  */
		GRAPH_SetVSizeX(hGraph, Oscilloscope_ScaleSizeX);
		GRAPH_SetVSizeY(hGraph, Oscilloscope_ScaleSizeY);
		GRAPH_SetGridOffY(hGraph, Oscilloscope_ScaleSizeY / 2);
		/* 创建示波器数据  */
		for (i = 0; i < 8; i++)
		{
			hData[i] = GRAPH_DATA_YT_Create(Data_Color[i],		/* 数据曲线颜色 */
				Oscilloscope_ScaleSizeY,					/* 数据项的最大数 */
				0,											/* 指向要添加到对象的数据的指针 */
				0);											/* 要添加的数据项数 */
			GRAPH_DATA_YT_SetAlign(hData[i], GRAPH_ALIGN_LEFT);
		}
		GRAPH_AttachData(hGraph, hData[0]);
		/* 创建示波器显示区坐标  */
		hScale_y = GRAPH_SCALE_Create(Oscilloscope_ScalePos, GUI_TA_RIGHT, GRAPH_SCALE_CF_VERTICAL, Oscilloscope_ScaleTickDist);
		GRAPH_SCALE_SetFactor(hScale_y, Oscilloscope_ScaleFactor);
		GRAPH_SCALE_SetOff(hScale_y, Oscilloscope_ScaleSizeY / 2);
		GRAPH_SCALE_SetTextColor(hScale_y, GUI_BLACK);
		#if GUI_LANGUAGE > 0u
			GRAPH_SCALE_SetFont(hScale_y, &GUI_FontHZ16);
		#else
			GRAPH_SCALE_SetFont(hScale_y, GUI_FONT_16B_1);
		#endif
		GRAPH_AttachScale(hGraph, hScale_y);
		/* 初始化ADC通道1选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Enable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道1:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel1:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道2选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_2_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道2:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel2:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道3选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_3_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道3:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel3:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道4选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_4_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道4:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel4:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道5选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_5_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道5:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel5:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道6选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_6_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道6:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel6:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道7选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_7_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道7:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel7:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道8选择框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_8_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Channel_Disable);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "通道8:");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Channel8:");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化ADC通道1文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道2文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_2_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道3文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_3_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道4文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_4_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道5文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_5_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道6文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_6_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道7文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_7_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化ADC通道8文本框 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_8_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		TEXT_SetText(hItem, "0.000V");
		/* 初始化示波器图标标题文本 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Title_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, "电压波形图像");
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetText(hItem, "Voltage waveform image");
		#endif
		/* 示波器设置按钮 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Settings_BUTTON);
		BUTTON_SetText(hItem, "");
		BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bm_settings);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bm_settings);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bm_settings);
		/* 示波器保持按钮 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Pause_BUTTON);
		BUTTON_SetText(hItem, "");
		BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmpause);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmpause);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmpause);
		/* 示波器切换按钮 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Switch_BUTTON);
		BUTTON_SetText(hItem, "");
		BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmSwitch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmSwitch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmSwitch);
		/* 示波器保存按钮 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Clear_BUTTON);
		#if GUI_LANGUAGE > 0u
			BUTTON_SetFont(hItem, &GUI_FontHZ24);
			BUTTON_SetText(hItem, "清空");
		#else
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);
			BUTTON_SetText(hItem, "Clear");
		#endif
		/* 示波器保存按钮 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Save_BUTTON);
		#if GUI_LANGUAGE > 0u
			BUTTON_SetFont(hItem, &GUI_FontHZ24);
			BUTTON_SetText(hItem, "保存");
		#else
			BUTTON_SetFont(hItem, GUI_FONT_24B_1);
			BUTTON_SetText(hItem, "Save");
		#endif
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					//清屏
		break;

	case WM_TIMER:
		#if GUI_OPERATING > 0U
			if (Oscilloscope_Status_bit == Oscilloscope_Running)
			{
				if (Oscilloscope_Mode_bit == Normal_Mode)
				{
					AD7606_ReadNowAdc();
					AD7606_StartConvst();
					for (i = 0; i < 8; i++)
					{
						Channel_Data[i] = (float)(g_tAD7606.sNowAdc[i] * 5 * (Oscilloscope_Range_bit + 1)) / 32768;
						sprintf(buf, "%0.3f V", Channel_Data[i]);
						TEXT_SetText(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_TEXT + i), buf);
						GRAPH_DATA_YT_AddValue(hData[i], 20 * Channel_Data[i] + Oscilloscope_ScaleSizeY / 2);
					}
				}
				else
				{
					printf("FIFO模式未制作\n\r");
				}
			}	
		#else
			if (Oscilloscope_Status_bit == Oscilloscope_Running)
			{
				for (i = 0; i < 8; i++)
				{
					if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_CHECKBOX + i)))
					{
						GRAPH_DATA_YT_AddValue(hData[i], 50 * (i + 1));
					}
				}
			}
		#endif
		/* 执行窗口无效化，会触发执行WM_PAINT消息 */
		WM_InvalidateRect(WM_GetClientWindow(hWin), &rOscilloscope);
		WM_InvalidateRect(WM_GetClientWindow(hWin), &rData);
		WM_RestartTimer(pMsg->Data.v, 100);
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件ID */
		Id = WM_GetId(pMsg->hWinSrc);
		/* 获取通知代码 */
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_APP_Oscilloscope_Settings_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hWinOscilloscope_Settings = FUN_Oscilloscope_Settings_Create(hWin);
				break;
			}
			break;

		case ID_APP_Oscilloscope_Pause_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				Oscilloscope_Status_bit = ~Oscilloscope_Status_bit;
				if (Oscilloscope_Status_bit == Oscilloscope_Running)
				{
					hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Pause_BUTTON);
					BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmpause);
					BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmpause);
					BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmpause);
				}
				else
				{
					hItem = WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Pause_BUTTON);
					BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmplay);
					BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmplay);
					BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmplay);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Switch_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		case ID_APP_Oscilloscope_Save_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;

		case ID_APP_Oscilloscope_Clear_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				for (i = 0; i < 8; i++)
				{
					if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_CHECKBOX + i)))
					{
						GRAPH_DATA_YT_Clear(hData[i]);
					}
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_1_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_1_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[0]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[0]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_2_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_2_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[1]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[1]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_3_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_3_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[2]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[2]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_4_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_4_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[3]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[3]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_5_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_5_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[4]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[4]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_6_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_6_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[5]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[5]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_7_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_7_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[6]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[6]);
				}
				break;
			}
			break;

		case ID_APP_Oscilloscope_Channel_8_CHECKBOX:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				if (CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_APP_Oscilloscope_Channel_8_CHECKBOX)))
				{
					GRAPH_AttachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[7]);
				}
				else
				{
					GRAPH_DetachData(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), hData[7]);
				}
				break;
			}
			break;
		}
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */


/**
  * @brief 示波器设置窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbOscilloscope_Settings(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;
	char buf[30];

	(void)NCode;
	(void)Id;

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		/* app窗口初始化 */
		#if GUI_LANGUAGE > 0u
			FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);                                  //窗口文本字体
			FRAMEWIN_SetText(hWin, "示波器设置");                                   //窗口文本
		#else
			FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
			FRAMEWIN_SetText(hWin, "Oscilloscope Settings");                        //窗口文本
		#endif
		FRAMEWIN_SetTextAlign(hWin, GUI_TA_HCENTER | GUI_TA_VCENTER);                         //标题栏文本对齐方式
		FRAMEWIN_SetTitleHeight(hWin, Oscilloscope_Settings_BAR_HIGHT);
		FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
		FRAMEWIN_AddMinButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);		//最小化按钮
		FRAMEWIN_SetMoveable(hWin, 1);								//窗口可移动
		FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
		/* 初始化显示区外观文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Appearance_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, "显示区外观设置:");
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetText(hItem, "Appearance Settings:");
		#endif
		/* 初始化显示区外观勾选按钮 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_GridVis_CHECKBOX);
		CHECKBOX_SetFocusColor(hItem, GUI_WHITE);
		CHECKBOX_SetState(hItem, Grid_Visible_bit);
		#if GUI_LANGUAGE > 0u
			CHECKBOX_SetText(hItem, "显示区网格可见");
			CHECKBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			CHECKBOX_SetText(hItem, "Grid Visible");
			CHECKBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化显示区外观下拉控件 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Grid_DROPDOWN);
		#if GUI_LANGUAGE > 0u             
				DROPDOWN_SetFont(hItem, &GUI_FontHZ24);
				DROPDOWN_AddString(hItem, "使用虚线网格");
				DROPDOWN_AddString(hItem, "使用点划线网格");
				DROPDOWN_AddString(hItem, "使用双点划线网格");
				DROPDOWN_AddString(hItem, "使用圆点网格");
				DROPDOWN_AddString(hItem, "使用实线网格");
		#else
				DROPDOWN_SetFont(hItem, GUI_FONT_24B_1);
				DROPDOWN_AddString(hItem, "Use a dash grid");
				DROPDOWN_AddString(hItem, "Use a dashdot grid");
				DROPDOWN_AddString(hItem, "Use a dashdotdot grid");
				DROPDOWN_AddString(hItem, "Use a dot grid");
				DROPDOWN_AddString(hItem, "Use a solid grid");
		#endif
		DROPDOWN_SetTextHeight(hItem, 25);
		DROPDOWN_SetItemSpacing(hItem, 5);
		DROPDOWN_SetSel(hItem, Grid_Type_bit);
		DROPDOWN_SetTextAlign(hItem, TEXT_CF_HCENTER);
		/* 初始化示波器量程文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Range_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, "示波器量程设置:");
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetText(hItem, "Oscilloscope range setting:");
		#endif
		/* 初始化示波器量程下拉控件 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Range_DROPDOWN);
		#if GUI_LANGUAGE > 0u             
				DROPDOWN_SetFont(hItem, &GUI_FontHZ24);
				DROPDOWN_AddString(hItem, "正负5V");
				DROPDOWN_AddString(hItem, "正负10V");
		#else
				DROPDOWN_SetFont(hItem, GUI_FONT_24B_1);
				DROPDOWN_AddString(hItem, "Plus or minus 5V");
				DROPDOWN_AddString(hItem, "Plus or minus 10V");
		#endif
		DROPDOWN_SetTextHeight(hItem, 25);
		DROPDOWN_SetItemSpacing(hItem, 5);
		DROPDOWN_SetSel(hItem, Oscilloscope_Range_bit);
		DROPDOWN_SetTextAlign(hItem, TEXT_CF_HCENTER);
		/* 初始化示波器采集方式文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Mode_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, "示波器采集方式设置:");
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetText(hItem, "Oscilloscope acquisition mode setting:");
		#endif
		/* 初始化示波器采集方式下拉控件 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Mode_DROPDOWN);
		#if GUI_LANGUAGE > 0u             
				DROPDOWN_SetFont(hItem, &GUI_FontHZ24);
				DROPDOWN_AddString(hItem, "普通工作模式");
				DROPDOWN_AddString(hItem, "FIFO工作模式");
		#else
				DROPDOWN_SetFont(hItem, GUI_FONT_24B_1);
				DROPDOWN_AddString(hItem, "Normal operating mode");
				DROPDOWN_AddString(hItem, "FIFO operating mode");
		#endif
		DROPDOWN_SetTextHeight(hItem, 25);
		DROPDOWN_SetItemSpacing(hItem, 5);
		DROPDOWN_SetSel(hItem, Oscilloscope_Mode_bit);
		DROPDOWN_SetTextAlign(hItem, TEXT_CF_HCENTER);
		/* 初始化示波器过采样率文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Oversampling_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			TEXT_SetText(hItem, "示波器过采样率设置:");
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			TEXT_SetText(hItem, "Oscilloscope oversampling rate setting:");
		#endif
		/* 初始化示波器采样率档位选择控件 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Oversampling_SPINBOX);
		SPINBOX_SetButtonSize(hItem, 50);
		SPINBOX_SetRange(hItem, 0, 6);
		SPINBOX_SetValue(hItem, Oscilloscope_Oversampling_bit);
		#if GUI_LANGUAGE > 0u             
			SPINBOX_SetFont(hItem, &GUI_FontHZ24);
		#else
			SPINBOX_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 初始化示波器过采样率值文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_OversamplingRate_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			if (Oscilloscope_Oversampling_bit == _NonOversampled)
			{
				TEXT_SetText(hItem, "无过采样");
			}
			else
			{
				sprintf(buf,"%d倍采样率", AD7606_Oversampling[Oscilloscope_Oversampling_bit - 1]);
				TEXT_SetText(hItem, buf);
			}
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			if (Oscilloscope_Oversampling_bit == _NonOversampled)
			{
				TEXT_SetText(hItem, "Unoversampled");
			}
			else
			{
				sprintf(buf, "%d X Oversampled", AD7606_Oversampling[Oscilloscope_Oversampling_bit - 1]);
				TEXT_SetText(hItem, buf);
			}
		#endif
		/* 初始化示波器采样率文本 */
		hItem = WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT);
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
			if (Oscilloscope_Oversampling_bit != _NonOversampled && Oscilloscope_Mode_bit == FIFO_Mode)
			{
				sprintf(buf, "采样率:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit]/1000);
				TEXT_SetText(hItem, buf);
			}
			else
			{
				TEXT_SetText(hItem, "");
			}
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
			if (Oscilloscope_Oversampling_bit != _NonOversampled && Oscilloscope_Mode_bit == FIFO_Mode)
			{
				sprintf(buf, "Sampling:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit] / 1000);
				TEXT_SetText(hItem, buf);
			}
			else
			{
				TEXT_SetText(hItem, "");
			}
		#endif
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					//清屏
		GUI_DrawGradientH(0, 0, Oscilloscope_Settings_WIDTH, Oscilloscope_Settings_HIGHT, GUI_WHITE, GUI_LIGHTBLUE);
		GUI_DrawGradientH(0, 15, 450, 20, GUI_LIGHTCYAN, GUI_LIGHTYELLOW);
		GUI_DrawGradientH(0, 90, 450, 95, GUI_LIGHTCYAN, GUI_LIGHTYELLOW);
		GUI_DrawGradientH(0, 165, 450, 170, GUI_LIGHTCYAN, GUI_LIGHTYELLOW);
		GUI_DrawGradientH(0, 240, 450, 245, GUI_LIGHTCYAN, GUI_LIGHTYELLOW);
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件ID */
		Id = WM_GetId(pMsg->hWinSrc);
		/* 获取通知代码 */
		NCode = pMsg->Data.v;
		switch (Id)
		{
			case ID_Oscilloscope_Settings_GridVis_CHECKBOX:
				switch (NCode)
				{
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_RELEASED:
					Grid_Visible_bit = (uint8_t)CHECKBOX_GetState(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_GridVis_CHECKBOX));
					GRAPH_SetGridVis(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), Grid_Visible_bit);
					break;
				}
				break;

			case ID_Oscilloscope_Settings_Grid_DROPDOWN:
				switch (NCode)
				{
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_SEL_CHANGED:
					Grid_Type_bit = (uint8_t)DROPDOWN_GetSel(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Grid_DROPDOWN));
					if (Grid_Type_bit == Grid_Solid)
					{
						GRAPH_SetLineStyleH(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_SOLID);
						GRAPH_SetLineStyleV(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_SOLID);
					}
					else if(Grid_Type_bit == Grid_Dash)
					{
						GRAPH_SetLineStyleH(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASH);
						GRAPH_SetLineStyleV(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASH);
					}
					else if(Grid_Type_bit == Grid_DashDot)
					{
						GRAPH_SetLineStyleH(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASHDOT);
						GRAPH_SetLineStyleV(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASHDOT);
					}
					else if (Grid_Type_bit == Grid_DASHDOTDOT)
					{
						GRAPH_SetLineStyleH(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASHDOTDOT);
						GRAPH_SetLineStyleV(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DASHDOTDOT);
					}
					else if (Grid_Type_bit == Grid_DOT)
					{
						GRAPH_SetLineStyleH(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DOT);
						GRAPH_SetLineStyleV(WM_GetDialogItem(hWinOscilloscopeTask, ID_APP_Oscilloscope_GRAPH), GUI_LS_DOT);
					}
					break;
				}
				break;

			case ID_Oscilloscope_Settings_Range_DROPDOWN:
				switch (NCode)
				{
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_SEL_CHANGED:
					Oscilloscope_Range_bit = (uint8_t)DROPDOWN_GetSel(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Range_DROPDOWN));
					#if GUI_OPERATING > 0U
						AD7606_SetInputRange(Oscilloscope_Range_bit);	/* 0表示输入量程为正负5V, 1表示正负10V */
					#endif
					break;
				}
				break;

			case ID_Oscilloscope_Settings_Mode_DROPDOWN:
				switch (NCode)
				{
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_SEL_CHANGED:
					Oscilloscope_Mode_bit = (uint8_t)DROPDOWN_GetSel(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Mode_DROPDOWN));
					#if GUI_OPERATING > 0U
						if (Oscilloscope_Mode_bit == FIFO_Mode)
						{
							AD7606_StartRecord(AD7606_SampleFreq[Oscilloscope_Oversampling_bit]);	/* 启动100kHz采样速率 */
							AD7606_SetOS(Oscilloscope_Oversampling_bit);       /* 设置无过采样 */
							printf("AD7606进入FIFO工作模式 (%s 8通道同步采集)...\r\n", AD7606_SampleStr[Oscilloscope_Oversampling_bit]);
						}
						else 
						{
							AD7606_StopRecord();	/* 停止记录 */
							AD7606_SetOS(Oscilloscope_Oversampling_bit);
							printf("AD7606进入普通工作模式(定时8通道同步采集)...\r\n");
						}
					#endif
					if (Oscilloscope_Mode_bit == FIFO_Mode && Oscilloscope_Oversampling_bit != _NonOversampled)
					{
						#if GUI_LANGUAGE > 0u
							sprintf(buf, "采样率:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit] / 1000);
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), buf);
						#else
							sprintf(buf, "Sampling:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit] / 1000);
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), buf);
						#endif
					}
					break;
				}
				break;

			case ID_Oscilloscope_Settings_Oversampling_SPINBOX:
				switch (NCode)
				{
				case WM_NOTIFICATION_CLICKED:
					break;
				case WM_NOTIFICATION_VALUE_CHANGED:
					Oscilloscope_Oversampling_bit = (uint8_t)SPINBOX_GetValue(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_Oversampling_SPINBOX));
					#if GUI_OPERATING > 0U
						AD7606_SetOS(Oscilloscope_Oversampling_bit);
						if (Oscilloscope_Mode_bit == FIFO_Mode)
						{
							AD7606_StartRecord(AD7606_SampleFreq[Oscilloscope_Oversampling_bit]);	/* 启动当前过采样下最高速度 */
						}
					#endif
					#if GUI_LANGUAGE > 0u
						if (Oscilloscope_Oversampling_bit == _NonOversampled)
						{
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_OversamplingRate_TEXT), "无过采样");
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), "");
						}
						else
						{
							sprintf(buf,"%d倍采样率", AD7606_Oversampling[Oscilloscope_Oversampling_bit - 1]);
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_OversamplingRate_TEXT), buf);
							if (Oscilloscope_Mode_bit == FIFO_Mode)
							{
								sprintf(buf, "采样率:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit]/1000);
								TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), buf);
							}
						}
					#else
						if (Oscilloscope_Oversampling_bit == _NonOversampled)
						{
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_OversamplingRate_TEXT), "Unoversampled");
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), "");
						}
						else
						{
							sprintf(buf, "%d X Oversampled", AD7606_Oversampling[Oscilloscope_Oversampling_bit - 1]);
							TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_OversamplingRate_TEXT), buf);
							if (Oscilloscope_Mode_bit == FIFO_Mode)
							{
								sprintf(buf, "Sampling:%0.3f Ksps", (float)AD7606_SampleFreq[Oscilloscope_Oversampling_bit] / 1000);
								TEXT_SetText(WM_GetDialogItem(hWin, ID_Oscilloscope_Settings_SamplingRate_TEXT), buf);
							}
						}
					#endif
					break;
				}
				break;
		}
		break;

	case WM_DELETE:
		break;

	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */
/************************************************************************************************************************
*
*       公共代码
*
*************************************************************************************************************************
*/
/**
  * @brief 示波器APP窗口创建函数
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Oscilloscope_Create(void)
{
	WM_HWIN hWin;
	WM_HWIN hTimer;
	(void)hTimer;    //空指针
	hWin = GUI_CreateDialogBox(Dialog_APP_Oscilloscope_Create, GUI_COUNTOF(Dialog_APP_Oscilloscope_Create), _cbAPP_Oscilloscope, WM_HBKWIN, 0, 0);
	hTimer = WM_CreateTimer(WM_GetClientWindow(hWin), 0, 1000, 0);       //创建定时器
	#if GUI_OPERATING > 0u
		bsp_InitAD7606();
		AD7606_StartConvst();	
	#endif
	return hWin;
}

/**
  * @brief 示波器设置窗口创建函数
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_Oscilloscope_Settings_Create(WM_HWIN hparents)
{
	WM_HWIN hWin;
	hWin = GUI_CreateDialogBox(Dialog_Oscilloscope_Settings_Create, GUI_COUNTOF(Dialog_Oscilloscope_Settings_Create), _cbOscilloscope_Settings, hparents, 0, 0);
	return hWin;
}
/*************************** End of file ****************************/
