/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
#include "DIALOG.h"
#include "GUI_Main.h"
#include "GUI_Music_DLG.h"


/* 不同定时器的句柄 */
#define ID_TIMER_SPEC       0
#define ID_TIMER_PROCESS    1
/* 歌曲路径字符长度 */
#define MusicPathSzie       100 

/*
*********************************************************************************************************
*				                    引用外部变量和函数
*********************************************************************************************************
*/
#if GUI_OPERATING > 0u
	/* 音乐任务TCB */
	extern OS_TCB  AppTaskMusicTCB;
#endif

/*
*********************************************************************************************************
*				                         变量
*********************************************************************************************************
*/
#if GUI_OPERATING > 0u
	static uint8_t s_MusicName[MusicPathSzie] = { 0 }; /* 用于记录当前播放的歌曲 */
	const char s_MusicPathDir[] = { "0:/Music/" };     /* 存储器中歌曲存放的路径 */
	static MusicMsg_T s_tMusicMsg;            		 /* 用于给音乐播放任务发消息，发送音乐类型和歌曲路径 */
#endif
static uint8_t s_ucPlayStatus = 0; 	      		 /* 播放器的开始和暂停按钮状态，0表示暂停，1表示运行 */


extern GUI_CONST_STORAGE GUI_BITMAP bmplay;
extern GUI_CONST_STORAGE GUI_BITMAP bmpause;
extern GUI_CONST_STORAGE GUI_BITMAP bmprevious;
extern GUI_CONST_STORAGE GUI_BITMAP bmnext;

#if GUI_OPERATING > 0u
	FILINFO* musicefile;               //文件信息
	extern FILINFO* wavfileinfo;    //文件信息
	extern uint32_t *wavoffsettbl;	//音乐offset索引表
	extern uint16_t totwavnum; 		//音乐文件总数
	extern uint16_t curindex;		//当前索引 
	//extern __wavctrl wavctrl;		//WAV控制结构体
#endif

/* 歌曲名称 */
#if GUI_LANGUAGE == 0u
	static char* Song_List[10] = {"music1","music2" ,"music3" ,"music4" ,"music5" ,"music6" ,"music7" ,"music8" ,"music9" ,"music10" };
#endif
/*------------------------------------------------------------------------------------------*/
/*-------------------------------------  回调函数   ----------------------------------------*/
/*------------------------------------------------------------------------------------------*/
/**
  * @brief 音乐窗口按钮回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbMusicButton(WM_MESSAGE* pMsg, int _uiNum, char* _pName)
{
	WM_HWIN hItem;
	char buf[40];

	#if GUI_LANGUAGE > 0u
		OS_ERR  err;
	#endif

	hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Song_TEXT);
	TEXT_SetText(hItem, _pName);

	#if GUI_LANGUAGE > 0u
		/* 将歌曲完整的路径复制到缓冲s_MusicName里面 */
		memset(s_MusicName, 0, MusicPathSzie);
		strcpy((char*)s_MusicName, s_MusicPathDir);
		strcat((char*)s_MusicName, _pName);
		//printf_audiodbg("path:%s\r\n", s_MusicName);
	#endif

	/* 显示当前歌曲播放序号和总的歌曲数量 */
	hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Select_DROPDOWN);
	sprintf(buf, "%d/%d", _uiNum + 1, DROPDOWN_GetNumItems(hItem));
	hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Number_TEXT);
	TEXT_SetText(hItem, buf);

	#if GUI_LANGUAGE > 0u
		/* 发消息，退出当前音乐播放 */
		OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
			(OS_FLAGS)MusicTaskAudioReturn_6,
			(OS_OPT)OS_OPT_POST_FLAG_SET,
			(OS_ERR*)&err);

		s_tMusicMsg.ucName = (uint8_t*)s_MusicName;
		if (strstr((char*)s_MusicName, ".WAV") || strstr((char*)s_MusicName, ".wav"))
		{
			/* WAV歌曲 */
			s_tMusicMsg.ucType = MusicType_WAV;
		}
		else if (strstr((char*)s_MusicName, ".MP3") || strstr((char*)s_MusicName, ".mp3"))
		{
			/* MP3歌曲 */
			s_tMusicMsg.ucType = MusicType_MP3;
		}
		else if (strstr((char*)s_MusicName, ".FLAC") || strstr((char*)s_MusicName, ".flac"))
		{
			/* FLAC歌曲 */
			s_tMusicMsg.ucType = MusicType_FLAC;
		}

		/* 发消息，播放新歌 */
		OSTaskQPost(&AppTaskMusicTCB,
			(void*)&s_tMusicMsg,   /* 数据地址 */
			sizeof(s_tMusicMsg),    /* 数据字节数，也可以不是字节数，保证发送和接收统一即可 */
			OS_OPT_POST_FIFO,
			&err);

		if (err == OS_ERR_NONE)
		{
			/* 根据按钮按下或者播放的状态发送消息 */
			if (s_ucPlayStatus == 1)
			{
				OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
					(OS_FLAGS)MusicTaskAudioPlay_5,
					(OS_OPT)OS_OPT_POST_FLAG_SET,
					(OS_ERR*)&err);
			}
			else
			{
				OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
					(OS_FLAGS)MusicTaskAudioStart_8,
					(OS_OPT)OS_OPT_POST_FLAG_SET,
					(OS_ERR*)&err);

			}

			/* 更新播放时间和歌曲信息 */
			hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Music_PROGBAR);
			PROGBAR_SetMinMax(hItem, 0, g_tWav.uiTotalTime);
			PROGBAR_SetValue(hItem, 0);

			hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Time_TEXT);
			sprintf(buf, "%02d:%02d/%02d:%02d", 0, 0, g_tWav.uiTotalTime / 60, g_tWav.uiTotalTime % 60);
			TEXT_SetText(hItem, buf);
		}
	#endif
}
/* function end */

/**
  * @brief 音乐播放——应用窗口回调函数
  * @note 无
  * @param WM_MESSAGE* pMsg  GUI消息
  * @retval 无
  */
static void _cbAPP_Music(WM_MESSAGE* pMsg)
{
	WM_HWIN hItem;
	WM_HWIN hWin;
	int NCode;
	int Id;
	static WM_HTIMER hTimerSpec;
	static WM_HTIMER hTimerProcess;
	static int  MusicPlayNum = 0;
	char buf[MusicPathSzie + 20];
	char Volume_str[30];
	#if	GUI_OPERATING > 0u
		OS_ERR  err;
		char searchbuf[50];
		char *fn;
		DIR DirInf;
		FILINFO finfo;
	#else
		uint8_t i;
	#endif
	
	(void) hTimerSpec;
	(void) hTimerProcess;

	hWin = pMsg->hWin;

	switch (pMsg->MsgId)
	{
	case WM_INIT_DIALOG:
		#if APP_Music_WINDOW_DEFAULT > 0u
			/* app窗口初始化 */
			FRAMEWIN_SetBarColor(hWin, 1, NEW_APP_BAR_COLOR_ENALBE);                //窗口标题栏颜色
			FRAMEWIN_SetBarColor(hWin, 0, NEW_APP_BAR_COLOR_UNENALBE);
			#if GUI_LANGUAGE > 0u
				FRAMEWIN_SetFont(hWin, &GUI_FontHZ24);                                  //窗口文本字体
				FRAMEWIN_SetText(hWin, "音乐播放器");                                     //窗口文本
			#else
				FRAMEWIN_SetFont(hWin, NEW_APP_BAR_FONT);                               //窗口文本字体
				FRAMEWIN_SetText(hWin, "Music player");                                      //窗口文本
			#endif
			FRAMEWIN_SetTextAlign(hWin, NEW_APP_BAR_ALIGN);                         //标题栏文本对齐方式
			FRAMEWIN_SetTitleHeight(hWin, NEW_APP_BAR_HIGHT);
			/* 初始化窗口性质 */
			if (NEW_APP_CLOSEBUTTON > 0u)
			{
				FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);    //关闭按钮
			}
			if (NEW_APP_ACTIVE > 0u)
			{
				FRAMEWIN_SetActive(hWin, 1);                                //窗口激活
			}
		#else
			/* 用户定义区 */
			/* 用户定义区结束 */
		#endif
		/* 定时器初始化 */
		hTimerSpec = WM_CreateTimer(pMsg->hWin, ID_TIMER_SPEC, 20, 0);
		hTimerProcess = WM_CreateTimer(pMsg->hWin, ID_TIMER_PROCESS, 100, 0);
		/* 歌曲列表初始化 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
		DROPDOWN_SetTextHeight(hItem, 25);
		#if GUI_LANGUAGE > 0u              //设置歌曲列表字体
				DROPDOWN_SetFont(hItem, &GUI_FontHZ24);
		#else
				DROPDOWN_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		DROPDOWN_SetAutoScroll(hItem, 1);      //设置歌曲列表滚轮
		DROPDOWN_SetScrollbarWidth(hItem, 30);
		DROPDOWN_SetTextAlign(hItem, TEXT_CF_VCENTER);
		#if GUI_LANGUAGE == 0u          //载入歌曲列表
		for (i = 0; i < 10; i++)
		{
			DROPDOWN_AddString(hItem, Song_List[i]);
		}
		#else
			/* 搜索WAV和MP3歌曲添加到listview控件上 */
			strncpy(searchbuf, s_MusicPathDir, strlen(s_MusicPathDir) - 1);
			searchbuf[strlen(s_MusicPathDir) - 1] = '\0';
			if (f_opendir(&DirInf, searchbuf) == FR_OK)
			{
				while (f_readdir(&DirInf, &finfo) == FR_OK)
				{
					if (!finfo.fname[0]) break;

					if (finfo.fattrib & AM_ARC)
					{
						/* 检索WAV文件，并将WAV播放时间计算出来 */
						if (strstr(finfo.fname, ".wav") || strstr(finfo.fname, ".WAV"))
						{
							#if _USE_LFN
								fn = *finfo.fname ? finfo.fname : finfo.fname;
							#else
								fn = finfo.fname;
							#endif
							DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN), (const char*)fn);
						}

						/* 检索MP3文件，并将MP3播放时间计算出来 */
						if (strstr(finfo.fname, ".MP3") || strstr(finfo.fname, ".mp3"))
						{
							#if _USE_LFN
								fn = *finfo.fname ? finfo.fname : finfo.fname;
							#else
								fn = finfo.fname;
							#endif
							DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN), (const char*)fn);
						}
						/* 检索flac文件，并将flac播放时间计算出来 */
						if (strstr(finfo.fname, ".FLAC") || strstr(finfo.fname, ".flac"))
						{
							#if _USE_LFN
								fn = *finfo.fname ? finfo.fname : finfo.fname;
							#else
								fn = finfo.fname;
							#endif
							DROPDOWN_AddString(WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN), (const char*)fn);
						}
					}
				}
			}
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Music_PROGBAR);      //初始化歌曲进度条
		PROGBAR_SetText(hItem, "");
		PROGBAR_SetSkinClassic(hItem);
		PROGBAR_SetBarColor(hItem, 0, GUI_BLUE);
		PROGBAR_SetBarColor(hItem, 1, GUI_WHITE);
		#if	GUI_OPERATING > 0u

		#else
			PROGBAR_SetMinMax(hItem, 0, 600);
			PROGBAR_SetValue(hItem, 200);
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Previous_BUTTON);  //初始化上一首按钮
		BUTTON_SetText(hItem, "");
		BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmprevious);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmprevious);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmprevious);
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Next_BUTTON);      //初始化下一首按钮
		BUTTON_SetText(hItem, "");
		BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmnext);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmnext);
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmnext);
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Play_BUTTON);     //初始化播放、暂停按钮
		BUTTON_SetText(hItem, "");
		if (!s_ucPlayStatus)
		{
			BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmplay);
			BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmplay);
			BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmplay);
		}
		else
		{
			BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmpause);
			BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmpause);
			BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmpause);
		}
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Song_TEXT);      //初始化歌曲名称文本
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		#if GUI_OPERATING > 0u
		#else
			TEXT_SetText(hItem, "Song Title");
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Number_TEXT);    //初始化歌曲序号文本
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		#if GUI_OPERATING > 0u
		#else
			TEXT_SetText(hItem, "1/24");
		#endif
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Time_TEXT);     //初始化歌曲播放时间文本
		#if GUI_LANGUAGE > 0u
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		#if GUI_OPERATING > 0u
		#else
			TEXT_SetText(hItem, "01:30/04:30");
		#endif
		/* 扬声器音量初始化 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER);   //初始化扬声器音量
		SLIDER_SetRange(hItem, 0, 63);
		SLIDER_SetValue(hItem, 0);
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_TEXT);
		#if GUI_LANGUAGE > 0u
			sprintf(Volume_str, "扬声器音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			sprintf(Volume_str, "Speaker Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 耳机左声道音量初始化 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER);      //初始化耳机左声道音量
		SLIDER_SetRange(hItem, 0, 63);
		SLIDER_SetValue(hItem, 50);
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_TEXT);
		#if GUI_LANGUAGE > 0u
			sprintf(Volume_str, "耳机左声道音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			sprintf(Volume_str, "Earphone Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		/* 耳机右声道音量初始化 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER);     //初始化耳机右声道音量
		SLIDER_SetRange(hItem, 0, 63);
		SLIDER_SetValue(hItem, 50);
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_TEXT);
		#if GUI_LANGUAGE > 0u
			sprintf(Volume_str, "耳机右声道音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, &GUI_FontHZ24);
		#else
			sprintf(Volume_str, "Earphone Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER)));
			TEXT_SetText(hItem, Volume_str);
			TEXT_SetFont(hItem, GUI_FONT_24B_1);
		#endif
		break;

	case WM_PAINT:
		GUI_SetBkColor(GUI_WHITE);
		GUI_Clear();					        //清屏	
		GUI_SetColor(GUI_LIGHTBLUE);
		GUI_DrawRect(99,269,700,290);
		break;

		/* 切换到下一首歌曲，音乐播放任务是高优先级任务，emWin任务是低优先级任务
		   当音乐播放任务通过函数WM_SendMessageNoPara发送消息给emWin任务时，会立即
		   执行此消息，这是因为emWin多任务的实现机制问题，看GUI_X_RTX.C文件即可。
		*/
	case MSG_NextMusic:
		/*1. 获取下一首要播放歌曲的序号 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
		MusicPlayNum++;
		if (MusicPlayNum == DROPDOWN_GetNumItems(hItem))
		{
			MusicPlayNum = 0;
		}
		/* 2. 获取歌曲名 */
		DROPDOWN_GetItemText(hItem, MusicPlayNum, buf, MusicPathSzie);

		/* 3. 显示歌曲名到界面上 */
		hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Song_TEXT);
		TEXT_SetText(hItem, (const char*)buf);

		/* 4. 将歌曲完整的路径复制到缓冲s_MusicName里面 */
		#if GUI_OPERATING > 0u
			memset(s_MusicName, 0, MusicPathSzie);
			strcpy((char*)s_MusicName, s_MusicPathDir);
			strcat((char*)s_MusicName, buf);
		#endif

		/* 5. 显示当前歌曲播放序号和总的歌曲数量 */
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
		sprintf(buf, "%d/%d", MusicPlayNum + 1, DROPDOWN_GetNumItems(hItem));
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Number_TEXT);
		TEXT_SetText(hItem, (const char*)buf);

		/* 6. 播放新歌 */
		#if GUI_OPERATING > 0u
			s_tMusicMsg.ucName = (uint8_t*)s_MusicName;
			if (strstr((char*)s_MusicName, ".WAV") || strstr((char*)s_MusicName, ".wav"))
			{
				/* WAV格式 */
				s_tMusicMsg.ucType = MusicType_WAV;
			}
//			else if (strstr((char*)s_MusicName, ".MP3") || strstr((char*)s_MusicName, ".mp3"))
//			{
//				/* MP3格式 */
//				s_tMusicMsg.ucType = MusicType_MP3;
//			}
//			else if (strstr((char*)s_MusicName, ".FLAC") || strstr((char*)s_MusicName, ".flac"))
//			{
//				/* FLAC格式 */
//				s_tMusicMsg.ucType = MusicType_FLAC;
//			}
			/*
			   给音乐任务发送歌曲路径，因为emWin多任务的执行，
			   此时音乐任务被挂起，回调消息执行完才会回到音乐任务 。
			*/
			OSTaskQPost(&AppTaskMusicTCB,
				(void*)&s_tMusicMsg,    /* 数据地址 */
				sizeof(s_tMusicMsg),     /* 数据字节数，也可以不是字节数，保证发送和接收统一即可 */
				OS_OPT_POST_FIFO,
				&err);
			if (err == OS_ERR_NONE)
			{
				/* 获取歌曲相关信息进行显示 */
				if (s_tMusicMsg.ucType == 1)
				{
					GetWavInfo(s_MusicName);
				}
//				else if (s_tMusicMsg.ucType == 2)
//				{
//					GetMP3Info(s_MusicName);
//				}
//				else if (s_tMusicMsg.ucType == 3)
//				{
//					GetFLACInfo(s_MusicName);
//				}
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Music_PROGBAR);
				PROGBAR_SetMinMax(hItem, 0, g_tWav.uiTotalTime);
				PROGBAR_SetValue(hItem, 0);

				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Time_TEXT);
				sprintf(buf, "%02d:%02d/%02d:%02d", 0, 0, g_tWav.uiTotalTime / 60, g_tWav.uiTotalTime % 60);
				TEXT_SetText(hItem, buf);

				/* 继续发消息，启动歌曲播放 */
				OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
					(OS_FLAGS)MusicTaskAudioPlay_5,  /* 设置bit5 */
					(OS_OPT)OS_OPT_POST_FLAG_SET,
					(OS_ERR*)&err);
			}
		#endif		
		break;

		/*  开始执行音乐播放 */
	case MSG_MusicStart:
		hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
		MusicPlayNum = DROPDOWN_GetNumItems(hItem);
		DROPDOWN_GetItemText(hItem, MusicPlayNum, buf, MusicPathSzie);
		_cbMusicButton(pMsg, MusicPlayNum, buf);
		break;

	case WM_NOTIFY_PARENT:
		/* 获取控件 ID */
		Id = WM_GetId(pMsg->hWinSrc);
		/* 获取消息内容 */
		NCode = pMsg->Data.v;
		switch (Id)
		{
		case ID_APP_Music_Previous_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				/* 调整到上一首歌曲 */
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
				if (MusicPlayNum == 0)
				{
					MusicPlayNum = DROPDOWN_GetNumItems(hItem);
				}
				MusicPlayNum--;
				DROPDOWN_GetItemText(hItem, MusicPlayNum, buf, MusicPathSzie);
				/* 执行相应操作 */
				_cbMusicButton(pMsg, MusicPlayNum, buf);
				break;
			}
			break;
		case ID_APP_Music_Play_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Play_BUTTON);
				if (s_ucPlayStatus == 1)
				{
					/* 暂停 */
					s_ucPlayStatus = 0;
					#if GUI_OPERATING > 0u
						g_tWav.ucDispUpdate = 0;
						OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
							(OS_FLAGS)MusicTaskAudioPause_2,
							(OS_OPT)OS_OPT_POST_FLAG_SET,
							(OS_ERR*)&err);
					#endif
					BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmplay);
					BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmplay);
					BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmplay);
				}
				else if (s_ucPlayStatus == 0)
				{
					/* 播放 */
					s_ucPlayStatus = 1;
					#if GUI_OPERATING > 0u
						g_tWav.ucDispUpdate = 1;
						OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
							(OS_FLAGS)MusicTaskAudioResume_3,
							(OS_OPT)OS_OPT_POST_FLAG_SET,
							(OS_ERR*)&err);
					#endif
					BUTTON_SetBitmap(hItem, BUTTON_BI_DISABLED, &bmpause);
					BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmpause);
					BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmpause);
				}
				break;
			}
			break;
		case ID_APP_Music_Next_BUTTON:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				/* 调整到下一首歌曲 */
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
				if (MusicPlayNum == 0)
				{
					MusicPlayNum = DROPDOWN_GetNumItems(hItem);
				}
				MusicPlayNum++;
				DROPDOWN_GetItemText(hItem, MusicPlayNum, buf, MusicPathSzie);
				/* 执行相应操作 */
				_cbMusicButton(pMsg, MusicPlayNum, buf);
				break;
			}
			break;
		case ID_APP_Music_Volume_Speaker_SLIDER:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_TEXT);
#if GUI_LANGUAGE > 0u
				sprintf(Volume_str, "扬声器音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
				sprintf(Volume_str, "Speaker Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
#if GUI_OPERATING > 0u
				wm8978_SetSpkVolume(SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_Speaker_SLIDER)));
#endif
				break;
			}
			break;
		case ID_APP_Music_Volume_LEFT_SLIDER:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_TEXT);
#if GUI_LANGUAGE > 0u
				sprintf(Volume_str, "耳机左声道音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
				sprintf(Volume_str, "Earphone Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
#if GUI_OPERATING > 0u
				wm8978_SetEarVolume(SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_LEFT_SLIDER)));
#endif
				break;
			}
			break;
		case ID_APP_Music_Volume_RIGHT_SLIDER:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_VALUE_CHANGED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_TEXT);
#if GUI_LANGUAGE > 0u
				sprintf(Volume_str, "耳机右声道音量:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, &GUI_FontHZ24);
#else
				sprintf(Volume_str, "Earphone Volume:%d", SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER)));
				TEXT_SetText(hItem, Volume_str);
				TEXT_SetFont(hItem, GUI_FONT_24B_1);
#endif
#if GUI_OPERATING > 0u
				wm8978_SetEarVolume(SLIDER_GetValue(WM_GetDialogItem(hWin, ID_APP_Music_Volume_RIGHT_SLIDER)));
#endif
				break;
			}
			break;
		case ID_APP_Music_Select_DROPDOWN:
			switch (NCode)
			{
			case WM_NOTIFICATION_CLICKED:
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			case WM_NOTIFICATION_SEL_CHANGED:
				hItem = WM_GetDialogItem(hWin, ID_APP_Music_Select_DROPDOWN);
#if GUI_OPERATING > 0u
				WM_SendMessageNoPara(hWin, MSG_MusicStart);
#endif

				break;
			}
			break;
		}
		break;

	case WM_TIMER:
		Id = WM_GetTimerId(pMsg->Data.v);
		switch (Id)
		{
			/* 时间到了更新频谱 */
		case ID_TIMER_SPEC:
			WM_RestartTimer(pMsg->Data.v, 20);
			break;

			/* 播放进度和播放时间更新 */
		case ID_TIMER_PROCESS:
			WM_RestartTimer(pMsg->Data.v, 100);
			#if GUI_OPERATING > 0u
				if (g_tWav.ucDispUpdate == 1)
				{
					OSFlagPost((OS_FLAG_GRP*)&FLAG_Music,
						(OS_FLAGS)MusicTaskAudioGetTime_7,
						(OS_OPT)OS_OPT_POST_FLAG_SET,
						(OS_ERR*)&err);
					
					sprintf(buf, "%02d:%02d/%02d:%02d", g_tWav.uiCurTime / 60, g_tWav.uiCurTime % 60, g_tWav.uiTotalTime / 60, g_tWav.uiTotalTime % 60);
					hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Time_TEXT);
					TEXT_SetText(hItem, buf);

					hItem = WM_GetDialogItem(pMsg->hWin, ID_APP_Music_Music_PROGBAR);
					PROGBAR_SetValue(hItem, g_tWav.uiCurTime);
				}
			#endif
			break;
		}
		break;

	case WM_DELETE:
		break;
	
	default:
		WM_DefaultProc(pMsg);
		break;
	}
}
/* function end */

/*------------------------------------------------------------------------------------------*/
/*-----------------------------------  窗口创建函数   --------------------------------------*/
/*------------------------------------------------------------------------------------------*/
/**
  * @brief 音乐播放APP窗口创建函数
  * @note 无
  * @param 无
  * @retval hWin：资源表中第一个控件的句柄
  */
WM_HWIN FUN_APP_Music_Create(void)
{
	WM_HWIN hWin;
	WM_HWIN hTimer;
	(void)hTimer;    //空指针
	hWin = GUI_CreateDialogBox(Dialog_APP_Music_Create, GUI_COUNTOF(Dialog_APP_Music_Create), _cbAPP_Music, WM_HBKWIN, 0, 0);
	hTimer = WM_CreateTimer(WM_GetClientWindow(hWin), 0, 500, 0);       //创建定时器
	return hWin;
}
/*************************** End of file ****************************/
